### DISCUSSION TITLE
How do I create an access entry?

### DISCUSSION THREAD

**Discussion by pablofilgueira91** [upbound/provider-aws#1450] [Q&A]
Hello, I am creating my EKS cluster with Crossplane, everything is created correctly, but when I enter the cluster through the AWS console I see the message in the image.
<img width="1394" alt="image" src="https://github.com/user-attachments/assets/9d51ee85-da28-46bb-8423-39bcb874e828">

How can I create the access entry with Crossplane? I can't find a way.
I tried to create the cluster from the AWS console and this is created automatically.

**Comment by turkenf** [comment]
We do not support the access entry resource now. However, after this [PR](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1273) is merged and released, you will be able to use it.

**Reply by pablofilgueira91** [reply]
Thanks for the reply, is there an estimated date for this to happen?

**Reply by turkenf** [reply]
Just released :) https://marketplace.upbound.io/providers/upbound/provider-aws-eks/v1.11.0/resources/eks.aws.upbound.io/AccessEntry/v1beta1

**Reply by pablofilgueira91** [reply]
Thank you, I'm trying it and I was able to create the AccessEntry correctly but I'm having an error with the AccessPolicyAssociation, could you help me?
This is the error I have in the AccessPolicyAssociation
![image](https://github.com/user-attachments/assets/4291cea2-d646-41d1-b531-9be52090a9ef)

This is my templates
```
apiVersion: eks.aws.upbound.io/v1beta1
kind: AccessEntry
metadata:
  name: access-entry
spec:
  forProvider:
    clusterNameRef:
      name: eksclustercrossplane
    principalArn: arn:aws:iam::518055008543:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AWSAdministratorAccess_4abe4318778ad858
    region: us-east-1
    type: STANDARD
---
apiVersion: eks.aws.upbound.io/v1beta1
kind: AccessPolicyAssociation
metadata:
  name: access-entry
spec:
  forProvider:
    accessScope:
      type: cluster
    clusterNameRef:
      name: eksclustercrossplane
    principalArnRef:
      name: access-entry
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    region: us-east-1
```

the configured Policy Arn exists in my AWS
![image](https://github.com/user-attachments/assets/cfadc8b8-6d73-45e1-8d57-7a412a2d0d83)

I appreciate any help
