### ISSUE TITLE
AWS KMS Key Alias not getting READY

### ISSUE THREAD

**Issue by nc-rajeshnair** [upbound/provider-aws#1009]
KMS Key Alias resource is not getting READY. 

```
NAME                                                      READY   SYNCED   EXTERNAL-NAME                    AGE
alias.kms.aws.upbound.io/aws-resource-claim-drdwr-fdt65   False   True     aws-resource-claim-drdwr-fdt65   15m

NAME                                                    READY   SYNCED   EXTERNAL-NAME                          AGE
key.kms.aws.upbound.io/aws-resource-claim-drdwr-tknb8   True    True     d469f615-1a55-4ee1-8189-b6d0752701e4   44m
```
**Composition**

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ecom.rajesh.forterro.com
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: forterro.com/v1
    kind: rajesh
  resources:
#Create a custom KMS for DMS
    - name: ecom-dms-kms-key
      base:
        apiVersion: kms.aws.upbound.io/v1beta1
        kind: Key
        metadata:
          name: ecom-dms-kms-key
          annotations:
            crossplane.io/external-name: ecom-dms-kms-key
          labels:
            name: ecom-dms-kms-key
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: default
          forProvider:
            region: us-east-1
            description: Custom KMS for DMS
        patches:
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.arn
            toFieldPath: status.dms.kms.kmsArn
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.id
            toFieldPath: status.dms.kms.kmsId
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.keyId
            toFieldPath: status.dms.kms.kmsKeyId
#Create an Alias for DMS Custom KMS 
    - name: ecom-dms-kms-alias          
      base: 
        apiVersion: kms.aws.upbound.io/v1beta1
        kind: Alias
        metadata:
          name: ecom-dms-kms-alias  
          # annotations:
          #   crossplane.io/external-name: ecom-dms-kms-alias   
          labels:
            name: ecom-dms-kms-alias 
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: default
          forProvider:
            region: us-east-1
            targetKeyId: 
        patches:
          - type: FromCompositeFieldPath
            fromFieldPath: status.dms.kms.kmsArn
            toFieldPath: spec.forProvider.targetKeyId
            policy:
              fromFieldPath: Required
```

**CompositionResourceDefinition**

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: rajeshs.forterro.com
spec:
  group: forterro.com
  names:
    kind: rajesh
    plural: rajeshs
  claimNames:
    kind: Rajeshecommerce
    plural: rajeshecommerces
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    environment:
                      type: string
            status:
              type: object
              properties:
                dms:
                  type: object
                  properties:
                    iam:
                      type: object
                      properties:
                        role:
                          type: object
                          properties:
                            arn:
                              type: string
                    kms: 
                      type: object
                      properties:
                        kmsArn:
                          type: string
                        kmsId:
                          type: string
                        kmsKeyId:
                          type: string 
```
**KMS Key Alias Resource Status**

```
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2023-12-05T20:57:04Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2023-12-05T20:57:04Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-12-05T21:11:11Z
    Message:               async create failed: failed to create the resource: [{0 creating KMS Alias (alias/aws-resource-claim-drdwr-fdt65): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, CreateAliasInput.TargetKeyId.
  []}]
    Reason:  AsyncCreateFailure
    Status:  False
    Type:    LastAsyncOperation
Events:
  Type    Reason                   Age                  From                                            Message
  ----    ------                   ----                 ----                                            -------
  Normal  PendingExternalResource  15m (x17 over 23m)   managed/kms.aws.upbound.io/v1beta1, kind=alias  Waiting for external resource existence to be confirmed
  Normal  CreatedExternalResource  3m2s (x21 over 23m)  managed/kms.aws.upbound.io/v1beta1, kind=alias  Successfully requested creation of external resource

```

### What environment did it happen in?

* Crossplane Version: v1.14
* Provider Version: v0.44.0
