### ISSUE TITLE
SecurityGroupRule not being proper created, In fact, it's stuck forever

### ISSUE THREAD

**Issue by lantier** [upbound/provider-aws#1045]
### What happened?
I'm trying to create a composition that has a SecurityGroup followed by a SecurityGroupRule. The former is created fine, but even referencing it into the latter by ID, or any tags, it got stuck indefinitely.

Describing the object, I can see this error:
```
Message:               async create failed: failed to create the resource: [{0 waiting for Security Group (sg-xxxxxxxxxxx) Rule (sgrule-xxxxxx) create: couldn't find resource  []}]
```

It detects and reads the SG just fine, but looking at the console, the sgrule was never created, even if it generates a new id.

On logs of the EC2 Family provider I can see this running forever:

```
crossplane-aws-upbound-ec2-4bad1441a535-5d794694c9-2cphp package-runtime 2023-12-27T09:11:12Z     DEBUG   provider-aws    Diff detected   {"uid": "ef7fd987-4c15-4458-9eb3-b219a9f3b938", "name": "loki-efs-tr6kg", "gvk": "ec2.aws.upbound.io/v1beta1, Kind=SecurityGroupRule", "instanceDiff": "*terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{\"description\":*terraform.ResourceAttrDiff{Old:\"\", New:\"Allow from Internal Network\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"from_port\":*terraform.ResourceAttrDiff{Old:\"\", New:\"2049\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, \"protocol\":*terraform.ResourceAttrDiff{Old:\"\", New:\"tcp\", NewComputed:false, NewRemoved:false, NewExtra:\"tcp\", RequiresNew:true, Sensitive:false, Type:0x0}, \"security_group_id\":*terraform.ResourceAttrDiff{Old:\"\", New:\"sg-xxxxxxx\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, \"security_group_rule_id\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"self\":*terraform.ResourceAttrDiff{Old:\"\", New:\"false\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, \"source_security_group_id\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, \"to_port\":*terraform.ResourceAttrDiff{Old:\"\", New:\"2049\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, \"type\":*terraform.ResourceAttrDiff{Old:\"\", New:\"ingress\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, RawConfig:cty.NilVal, RawState:cty.NilVal, RawPlan:cty.NilVal, Meta:map[string]interface {}(nil)}"}
crossplane-aws-upbound-ec2-4bad1441a535-5d794694c9-2cphp package-runtime 2023-12-27T09:11:12Z     DEBUG   provider-aws    Async create starting...        {"trackerUID": "ef7fd987-4c15-4458-9eb3-b219a9f3b938", "resourceName": "loki-efs-tr6kg", "tfID": ""}
crossplane-aws-upbound-ec2-4bad1441a535-5d794694c9-2cphp package-runtime 2023-12-27T09:11:12Z     DEBUG   provider-aws    Creating the external resource  {"uid": "ef7fd987-4c15-4458-9eb3-b219a9f3b938", "name": "loki-efs-tr6kg", "gvk": "ec2.aws.upbound.io/v1beta1, Kind=SecurityGroupRule"}
crossplane-aws-upbound-ec2-4bad1441a535-5d794694c9-2cphp package-runtime 2023/12/27 09:12:08 [TRACE] Waiting 10s before next try
crossplane-aws-upbound-ec2-4bad1441a535-5d794694c9-2cphp package-runtime 2023/12/27 09:12:18 [TRACE] Waiting 10s before next try
crossplane-aws-upbound-ec2-4bad1441a535-5d794694c9-2cphp package-runtime 2023/12/27 09:12:28 [TRACE] Waiting 10s before next try
```

### How can we reproduce it?
The composition has many resources, but even reducing it to just SG and SGRule is giving me the issue:

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: security-group
spec:
  writeConnectionSecretsToNamespace: crossplane
  compositeTypeRef:
    apiVersion: platform.xxxxx.internal/v1alpha1
    kind: xSecurityGroup
  patchSets:
    - name: AwsParameters
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
    - name: SecurityGroupParameters
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.name
    - name: SecurityGroupStatus
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.filesystem.securityGroupId
          policy:
            fromFieldPath: Required
  resources:
    base:
    - name: efs-security-group
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            name: # patched
            description: Allow access to EFS from the clusters private network
            vpcIdRef: 
              name: workloads
      readinessChecks:
        - matchCondition:
            status: 'True'
            type: Ready
          type: MatchCondition
      patches:
        - patchSetName: SecurityGroupParameters
          type: PatchSet
        - patchSetName: AwsParameters
          type: PatchSet
        - patchSetName: SecurityGroupStatus
          type: PatchSet

    - name: efs-sg-rule-2049
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            securityGroupIdSelector:
              matchControllerRef: true
            description: Allow access to EFS from private network
            fromPort: 2049
            toPort: 2049
            protocol: tcp
            type: ingress
            cirdBlocks: 
              - 10.0.0.0/8
            description: Allow from Internal Network
      readinessChecks:
        - matchCondition:
            status: 'True'
            type: Ready
          type: MatchCondition
      patches:
        - patchSetName: AwsParameters
          type: PatchSet
```

### What environment did it happen in?

* Crossplane Version: 1.14.5
* Provider Version: 0.46.1
* Kubernetes Version: 1.27
* Kubernetes Distribution: EKS
