### ISSUE TITLE
MSK-Kafka: secretArnRefs got overwrite by secretArnList

### ISSUE THREAD

**Issue by quanlk2511** [upbound/provider-aws#1047]
### What happened?
Hi team, I'm using kafka.aws.upbound.io/v1beta1. When creating ScramSecretAssociation resource, the secretArnRefs is overwritten by secretArnList. 

I want to use both options, since I have existed MSK secrets to associate, and want to create/associate new one via crossplane api.

### How can we reproduce it?
Here is my resource config:
```
apiVersion: kafka.aws.upbound.io/v1beta1
kind: ScramSecretAssociation
metadata:
  name: msk-secret-association
  labels:
    role: msk-secret-association
spec:
  deletionPolicy: Orphan
  forProvider:
    clusterArn: "arn:aws:kafka:ap-southeast-1:xxxxx:cluster/non-prod-common/xxxxx"
    region: ap-southeast-1
    secretArnList:
    - "arn:aws:secretsmanager:ap-southeast-1:xxxxx:secret:AmazonMSK_non-prod-common-xxxxx"
    secretArnRefs:
    - name: "non-prod-test-log"
    - name: "non-prod-dev-log"
  providerConfigRef:
    name: aws
``` 

``` 
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws
spec:
  credentials:
    source: IRSA
``` 

The secrets non-prod-test-log, non-prod-dev-log are created via secretsmanager.aws.upbound.io/v1beta1
``` 
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: non-prod-dev-log
spec:
  deletionPolicy: Orphan
  forProvider:
    name: AmazonMSK_non-prod-dev-log
    kmsKeyId: "arn:aws:kms:ap-southeast-1:xxxxx:key/xxxxx"
    region: ap-southeast-1
  providerConfigRef:
    name: aws
``` 

I'd expect all secrets: AmazonMSK_non-prod-common-xxxxx and non-prod-test-log, non-prod-dev-log to be associated, but only AmazonMSK_non-prod-common-xxxxx got associated.

Here is the status from resource:
``` 
Status:
  At Provider:
    Cluster Arn:  arn:aws:kafka:ap-southeast-1:xxxxx:cluster/non-prod-common/xxxxx
    Id:           arn:aws:kafka:ap-southeast-1:xxxxx:cluster/non-prod-common/xxxxx
    Secret Arn List:
      arn:aws:secretsmanager:ap-southeast-1:xxxxx:secret:AmazonMSK_non-prod-common-xxxxx
``` 

And if I remove secretArnList, secrets in secretArnRefs will be associated:

``` 
Status:
  At Provider:
    Cluster Arn:  arn:aws:kafka:ap-southeast-1:xxxxx:cluster/non-prod-common/xxxxx
    Id:           arn:aws:kafka:ap-southeast-1:xxxxx:cluster/non-prod-common/xxxxx
    Secret Arn List:
      arn:aws:secretsmanager:ap-southeast-1:xxxxx:secret:AmazonMSK_non-prod-dev-log
      arn:aws:secretsmanager:ap-southeast-1:xxxxx:secret:AmazonMSK_non-prod-test-log
``` 

### What environment did it happen in?

* Crossplane Version: 1.14.5
* Provider Version: AWS 0.45.0
* Kubernetes Version: v1.28.4-eks
* Kubernetes Distribution: EKS
* Platform version: eks.6
