### ISSUE TITLE
Elasticache ReplicationGroup fails when engineVersion is provided

### ISSUE THREAD

**Issue by zhodowanec** [upbound/provider-aws#1071]
### What happened?
ReplicationGroup resource fails to sync when a value for the `engineVersion` parameter is defined. 

Error message: 
- `'observe failed: cannot compute the instance diff: failed to get *terraform.InstanceDiff: error parsing old engine_version: Malformed version: '`

### How can we reproduce it?

ReplicationGroup

```yaml
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: ReplicationGroup
metadata:
  name: <cache-name>
spec:
  forProvider:
    atRestEncryptionEnabled: true
    automaticFailoverEnabled: true
    description: <description>
    engine: Redis
    engineVersion: "6.2.6"
    nodeType: cache.r5.large
    numNodeGroups: 1
    parameterGroupName: 
    port: 6379
    region: <region>
    replicasPerNodeGroup: 1
    subnetGroupNameRef:
      name: <cache-name>
    transitEncryptionEnabled: false
  providerConfigRef:
    name: <provider-config>
```

SubnetGroup

```yaml
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  name: <cache-name>
spec:
  forProvider:
    region: <region>
    subnetIds:
      - <subnet-id>
  providerConfigRef:
    name: <provider-config>
```

### What environment did it happen in?

* Crossplane Version: `v1.14.4`
* Provider Version: `v0.47.1`
* Kubernetes Version: `v1.27.8`
* Kubernetes Distribution: `EKS`
