### ISSUE TITLE
`Cluster.docdb.aws.upbound.io/v1beta1` : Provide password details as connection secret

### ISSUE THREAD

**Issue by cest-pas-faux** [upbound/provider-aws#1077]
### What problem are you facing?

The community provider allows us to write all the credentials of a created docdb cluster : 
```yaml
apiVersion: v1
kind: Secret
data:
  endpoint: xxxxxx
  password: xxxxxx
  port: xxxxxx
  readerEndpoint: xxxxxx
  username: xxxxxx
```
The official one does not provide the password, hence the secret generated is incomplete : 
```yaml
apiVersion: v1
kind: Secret
data:
  endpoint: xxxxxx
  port: xxxxxx
  readerEndpoint: xxxxxx
  username: xxxxxx
```

### How could Official AWS Provider help solve your problem?

Expose the password value obtained by [masterPasswordSecretRef](https://marketplace.upbound.io/providers/upbound/provider-aws-docdb/v0.47.1/resources/docdb.aws.upbound.io/Cluster/v1beta1#doc:spec-forProvider-masterPasswordSecretRef) to be used by `connectionDetails`
