### ISSUE TITLE
AWS Secrets Manager Provider Constantly Adds and Deletes Regional Replication

### ISSUE THREAD

**Issue by shelby-moore** [upbound/provider-aws#1079]
### What happened?
On upgrade to 0.47.1 (also observed the same behaviour in 0.46.0), the AWS Secrets Manager provider constantly removes regional replication for secrets and then adds it back. This results in a steep increase in billing costs for the AWS Secrets Manager API. Tailing the logs for the provider will show the constant creation and deletion of replication. Downgrading the provider to 0.43.0 resolved the issue.

### How can we reproduce it?
Create a [Secret](https://marketplace.upbound.io/providers/upbound/provider-aws-secretsmanager/v0.47.1/resources/secretsmanager.aws.upbound.io/Secret/v1beta1) resource with the replica config block set to replicate the secret to an additional region, ex:

```
---
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: my-secret
spec:
  deletionPolicy: Delete
  forProvider:
    name: my-secret
    region: us-east-1
    replica:
    - region: us-east-2
```

### What environment did it happen in?

* Crossplane Version: 0.14.5
* Provider Version: 0.47.1 (also observed for 0.46.0)
* Kubernetes Version: 1.28
* Kubernetes Distribution: EKS
