### ISSUE TITLE
[Bug]: regression: can't create Elasticache ReplicationGroup on v0.47.1

### ISSUE THREAD

**Issue by LCaparelli** [upbound/provider-aws#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

- elasticache.aws.upbound.io/v1beta1 - ReplicationGroup

### Resource MRs required to reproduce the bug

```
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: ReplicationGroup
metadata:
  name: reproducer
spec:
  deletionPolicy: Delete
  forProvider:
    applyImmediately: false
    automaticFailoverEnabled: true
    description: Cache replication reproducer
    engine: redis
    engineVersion: "7.0"
    nodeType: cache.t2.micro
    numNodeGroups: 1
    region: us-east-1
    replicasPerNodeGroup: 0
    securityGroupIds:
    - sg-SOME-SG
    snapshotRetentionLimit: 7
    subnetGroupName: SOME-SUBNET-GROUP
    transitEncryptionEnabled: false
  initProvider: {}
  managementPolicies:
  - '*'
```

### Steps to Reproduce

1. Update to v0.47.1
2. Apply provided MR

### What happened?

Failure to create, with:
```
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2024-01-16T20:33:14Z
    Message:               observe failed: cannot compute the instance diff: failed to get *terraform.InstanceDiff: error parsing old engine_version: Malformed version: 
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
```

### Crossplane Version

v1.14

### Provider Version

v0.47.1

### Additional Info

Rolling back to v0.46.1 prevents this from popping up. 

Looks like terraform state is being mangled at some point. Not sure if this is a crossplane-specific, or terraform-specific problem.
