### ISSUE TITLE
TransitGatewayVPCAttachment update subnetIdSelector to new labels does not work

### ISSUE THREAD

**Issue by Donimax** [upbound/provider-aws#1097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

TransitGatewayVPCAttachment.ec2.aws.upbound.io/v1beta1

### Resource MRs required to reproduce the bug

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: testing-vpc
spec:
  forProvider:
    region: us-west-1
    cidrBlock: 172.16.0.0/16
    tags:
      Name: testingVpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:

  labels:
    tgwa: test1
  name: test-subnet1
spec:
  forProvider:
    availabilityZone: us-west-1a
    cidrBlock: 172.16.1.0/24
    region: us-west-1
    vpcIdRef:
      name: testing-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    tgwa: test1
  name: test-subnet2
spec:
  forProvider:
    availabilityZone: us-west-1c
    cidrBlock: 172.16.2.0/24
    region: us-west-1
    vpcIdRef:
      name: testing-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    tgwa: test2
  name: test-subnet3
spec:
  forProvider:
    availabilityZone: us-west-1a
    cidrBlock: 172.16.3.0/24
    region: us-west-1
    vpcIdRef:
      name: testing-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    tgwa: test2
  name: test-subnet4
spec:
  forProvider:
    availabilityZone: us-west-1c
    cidrBlock: 172.16.4.0/24
    region: us-west-1
    vpcIdRef:
      name: testing-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: TransitGateway
metadata:
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    multicastSupport: enable
    region: us-west-1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: TransitGatewayVPCAttachment
metadata:
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    region: us-west-1
    subnetIdSelector:
      matchLabels:
        tgwa: test1
    transitGatewayIdRef:
      name: test
    vpcIdRef:
      name: testing-vpc


```
### Steps to Reproduce

- Create VPC with 4 subnets and transit gateway 
- First 2 subnets has labels `tgwa: test1` other 2 subnets has as label `tgwa: test2`
- create TransitGatewayVPCAttachment which has as subnetIdSelector matchLables `tgwa: test1` 
- Wait until everything is ready
- Change TransitGatewayVPCAttachment subnetIdSelector matchLables to `tgwa: test2` 

### What happened?

After changing the subnetIdSelector to the other 2 subnets it should update the TransitGatewayVPCAttachment resource to them.

### Crossplane Version

1.14.5

### Provider Version

0.47.1

### Kubernetes Version

v1.28.2

### Kubernetes Distribution

EKS
