### ISSUE TITLE
[Bug]: Problem importing ECS Clusters

### ISSUE THREAD

**Issue by daniel-maganto** [upbound/provider-aws#1101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

ecs.aws.upbound.io/v1beta1 - Cluster

### Resource MRs required to reproduce the bug
```
apiVersion: ecs.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    crossplane.io/external-name: dev-dev1
  labels:
    name: dev-dev1
    tenant: tenant1
  name: dev-dev1
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-central-1
  providerConfigRef:
    name: aws-admin-dev-account-upbound
```
### Steps to Reproduce

Create cluster using previous definition, then delete from the cluster and create again.

### What happened?

Instead to import the cluster using the metadata.name it informs error about ID we should use to import the external name using the ARN.

### Relevant Error Output Snippet

```shell
message: 'observe failed: failed to set the external-name of the managed resource
      during observe: failed to compute the external-name from the state map of the
      resource with the ID dev-dev1: terraform ID should be the ARN of the cluster'
    reason: ReconcileError
```

### Crossplane Version

1.14.5

### Provider Version

0.47.1

### Kubernetes Version

v1.28.2

### Kubernetes Distribution

EKS

**Comment by turkenf** [comment]
Hi @daniel-maganto,

Unless I'm missing something, I can't reproduce the issue with the steps below.
- Applied the following YAML and created the `Cluster.ecs.aws.upbound.io` resource:
```
apiVersion: ecs.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: example-devtest
spec:
  deletionPolicy: Orphan
  forProvider:
    region: us-west-1
```
*k get managed*
```
NAME                                         READY   SYNCED   EXTERNAL-NAME     AGE
cluster.ecs.aws.upbound.io/example-devtest   True    True     example-devtest   12m
```
- Deleted the resource from my cluster:
```
> k delete cluster.ecs.aws.upbound.io/example-devtest
cluster.ecs.aws.upbound.io "example-devtest" deleted
```
- Then I imported using external-name annotation:
```
apiVersion: ecs.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    crossplane.io/external-name: example-devtest
  name: example-devtest
spec:
  deletionPolicy: Orphan
  forProvider:
    region: us-west-1
```

I did not encounter any issues, is there a different step here than in your situation?

**Comment by dmaganto** [comment]
@turkenf doing exactly these steps I continue having the same error:

```
  conditions:
  - lastTransitionTime: "2024-01-23T22:02:43Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-01-23T22:02:43Z"
    message: 'observe failed: failed to set the external-name of the managed resource
      during observe: failed to compute the external-name from the state map of the
      resource with the ID example-devtest: terraform ID should be the ARN of the
      cluster'
    reason: ReconcileError
    status: "False"
    type: Synced
    ```
    Did you get a different status?

**Comment by turkenf** [comment]
Thank you for your quick response @dmaganto, 

> In any case, if I set the ARN I can import the resource, but at least in my understanding, this isn't the expected behavior.

You're right, this is not expected behavior. I was able to reproduce the error in version `0.47.1`, I tried it in the main branch in my previous attempt. 
I didn't look into exactly what caused this issue, but as far as I understand, it has been resolved. The package will be available in the next release.

Can you try to reproduce the issue in the package below which I created from the main branch?
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ecs
spec:
  package: turkenf/provider-aws-ecs:v0.48.0-rc.0.54.g88c1ae1d2
```
