### ISSUE TITLE
provider-aws-ecs: multiple unused taskDefinitions

### ISSUE THREAD

**Issue by denzhel** [upbound/provider-aws#1115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

ecs.aws.upbound.io/v1beta1 - TaskDefinition

### Resource MRs required to reproduce the bug

```
apiVersion: ecs.aws.upbound.io/v1beta1
kind: TaskDefinition
metadata:
  annotations:
    crossplane.io/external-name: stg-us-east-1-integrations-configurer-5k9kk
  name: stg-us-east-1-integrations-configurer-5k9kk-task-d17d9db6f1e5
spec:
  deletionPolicy: Delete
  forProvider:
    containerDefinitions: <jsonObject>
    cpu: "512"
    executionRoleArn: <roleARN>
    family: stg-us-east-1-integrations-configurer-5k9kk
    memory: "1024"
    networkMode: awsvpc
    region: us-east-1
    requiresCompatibilities:
    - FARGATE
    taskRoleArn: <roleARN>
    name: <providerConfigName>
```

### Steps to Reproduce

1. Create a task definition
2. Apply it using ArgoCD/Kubernetes and etc ..
3. Change one of the values inside the manifest, lets say cpu to 2048
4. Apply it again

Since the object is immutable, I had to use a hash inside the claim's name. 
Please do the same manually, change the `metadata.name` and add a hash at the end to create another revision.

Watch for another revision is created while the old one stays.
This can lead to many taskDefinitions just laying around while only one is in use

### What happened?

One used taskDefinitions while the others are just laying around Kubrenetes/ArgoCD
```
taskdefinition.ecs.aws.upbound.io/stg-us-east-1-inbound-alert-persistence-fhdp5-task-633b1f         True    True     stg-us-east-1-inbound-alert-persistence-fhdp5   6d20h
taskdefinition.ecs.aws.upbound.io/stg-us-east-1-inbound-alert-persistence-fhdp5-task-633b1fd561eb   True    True     stg-us-east-1-inbound-alert-persistence-fhdp5   6d10h
taskdefinition.ecs.aws.upbound.io/stg-us-east-1-inbound-alert-persistence-fhdp5-task-9581df         True    True     stg-us-east-1-inbound-alert-persistence-fhdp5   13d
taskdefinition.ecs.aws.upbound.io/stg-us-east-1-inbound-alert-persistence-fhdp5-task-b5d57a         True    True     stg-us-east-1-inbound-alert-persistence-fhdp5   12d
taskdefinition.ecs.aws.upbound.io/stg-us-east-1-inbound-alert-persistence-fhdp5-task-b5d57ad9e8ea   True    True     stg-us-east-1-inbound-alert-persistence-fhdp5   46h
```

Referencing the old issue I opened which led me to find a solution of creating new task Definitions 
https://github.com/upbound/provider-aws/issues/1061

### Crossplane Version

1.14.15

### Provider Version

0.47.1

### Kubernetes Version

v1.26.11-eks-8cb36c9

### Kubernetes Distribution

EKS

**Comment by dmaganto** [comment]
Are you using helm with it?? I was able to make it work using helm + a composition where I added a field with the hash from containerDefinitions and I used it in the name

**Comment by denzhel** [comment]
> Are you using helm with it?? I was able to make it work using helm + a composition where I added a field with the hash from containerDefinitions and I used it in the name

Hi @dmaganto ,

That's exactly what I did but new revisions are created and the old ones are not removed from ArgoCD/ Kubernetes:
```
k get managed
```

Can you share your config ? 

Mine is:
Templated claim:
```
apiVersion: example.io/v1alpha1
kind: EcsCluster
metadata:
  name: {{ printf "%s-%s" (ternary (printf "%s-%s" (index (regexSplit "-" $.Values.global.env 2) 0) $region ) $.Values.global.env $.Values.ecs.csAccount) $.Values.ecs.name }}
spec:
...
  taskDefinition:
    containerDefinitions: {{ $.Values.ecs.taskDefinition.containerDefinitions | toJson | quote }}
    containerDefinitionsHash: {{ sha256sum ($.Values.ecs.taskDefinition.containerDefinitions | toJson | quote  | trunc 12 }}
```

That's the patch I use on taskDefinition's composition:
```
        # define the name of the object using combination of two fields
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.name
              - fromFieldPath: spec.taskDefinition.containerDefinitionsHash
            strategy: string
            string:
              fmt: "%s-task-%s"
          toFieldPath: metadata.name
```

**Comment by dmaganto** [comment]
Ok, in my case to create the "magic" i have created another Composition only for TaskDefinition where I modify the composition name based on ContainerDefinition hash. With that helm removes the old object and only in the cluster remains the valid ones.

```
apiVersion: example.io/v1alpha1
kind: EcsTaskDef
metadata:
  name: my-service-{{ .Values.ecs.taskDefinition.containerDefinitions | trunc 12}}
spec:
...
    containerDefinitionsHash: {{ .Values.ecs.taskDefinition.containerDefinitions | trunc 12 }}
...
```

Then you can link with the ECS Service through the TaskDefinitionRef or TaskDefinitionSelector in the composition where you have it

**Comment by denzhel** [comment]
Thanks for the tip @dmaganto ! 
I'm seeing that you're not using claims, can you share why you've decided to do so ? I'm a bit confused on templating directly a XR via helm or templating a  XRC.

**Comment by denzhel** [comment]
But wait @dmaganto, how is it any different from what I do when I build the resources name here ?
```
       # define the name of the object using combination of two fields
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.name
              - fromFieldPath: spec.taskDefinition.containerDefinitionsHash
            strategy: string
            string:
              fmt: "%s-task-%s"
          toFieldPath: metadata.name
```

**Comment by dmaganto** [comment]
I use Claims mostly. And in this case is because the Composition always maintain the resources created by them (I didn't found any property that removes the object if name change)even if the name changes. But creating another Kubernetes object maintained by helm it removes the old one (task definition) because it is a new object for Kubernetes.

**Comment by denzhel** [comment]
I DM'd you on Crossplane's slack channel, is it possible to get your help? @dmaganto

**Comment by dmaganto** [comment]
Sure! Let's do it

**Comment by guyelia** [comment]
@denzhel  @dmaganto for the sake of documentation for others, if you can please share the solution here, it will be very helpful, thanks!

**Comment by dmaganto** [comment]
The main idea that I have followed is using this architecture. (Sorry for the diagram if something is not clear enough)
![image](https://github.com/upbound/provider-aws/assets/29373125/a0a900a1-e993-44d4-a31e-00924f073b2a)

**Comment by denzhel** [comment]
Sharing my solution:

![image](https://github.com/upbound/provider-aws/assets/33213077/082f9757-5a41-492e-9229-05c83fe410d2)

We've decided to create an ECS cluster + ECS service + ECS task definition per application.

Since we use Argo and have multiple sub applications and plan on creating resources in different sub applications, we've decided to split the Composition and XRD to one helm chart and have it run once using Helm/ArgoCD and another Helm chart that holds the claims.

Since the taskDefinition resource is in an other composition, meaning I can't use `status` field to share data between the resources, I had to use `matchLabels` and create a common value for coupling the Service and the taskDefinition. Each time the `containerDefinitions` object changes, the following will happen:
1. New containerDefinitionsHash will be generated
2. New taskDefinition resource will be created, replacing the old one
3. Service resource will be updated to trigger a new deployment with the new taskdefinition revision
--------
I've added this line to the `EcsClusterAndService` claim:
```
{{/* generate a hash from the containerDefinitions object  */}}
  containerDefinitionsHash: {{ $.Values.ecs.taskDefinition.containerDefinitions | toString | sha256sum | trunc 63 }}
```
This to to the `ecsclusterandservice` composition:
```
        # use labels to track down the taskDefinition
        - type: FromCompositeFieldPath
          fromFieldPath: spec.containerDefinitionsHash
          toFieldPath: spec.forProvider.taskDefinitionSelector.matchLabels["taskDefinition"]
```
And to the `xecsclustersandservices.example.io` XRD:
```
              containerDefinitionsHash:
                type: string
```
--------------
Then I moved to the `EcsTaskDefinition` claim, there is one important thing:
* Template the `metadata.name` object and use the generated hash as a suffix to make it unique
Added this to the `EcsTaskDefinition` claim:
```
metadata:
  name: {{ printf "%s-%s-%s" $.Values.global.env $.Values.ecs.name $.Values.ecs.taskDefinition.containerDefinitions | toString | sha256sum | trunc 12 }}
spec:
   containerDefinitionsHash: {{ $.Values.ecs.taskDefinition.containerDefinitions | toString | sha256sum | trunc 63 }}
```
Then I moved to the `ecstaskdefinition` composition, one important thing:
* Make sure `family` field is unique - I've discovered that if you give it a templated value that changes with each config change, the service will not be able to deploy the new revision (BUG??)

```
        # define labels
        - type: FromCompositeFieldPath
          fromFieldPath: spec.containerDefinitionsHash
          toFieldPath: metadata.labels["taskDefinition"]
        # resource specific
        - type: FromCompositeFieldPath
          fromFieldPath: spec.taskID
          toFieldPath: spec.forProvider.family
```
And to the `xectaskdefinition.example.io` XRD:
```
              containerDefinitionsHash:
                type: string
```

Once I've synced everything I discovered that I have one object per kind and old taskdefinitions are deleted and replaced with new ones. I also made sure Rolling Update works for the service - old tasks are deleted only when the new ones are healthy and running

Thanks @dmaganto for all the tips and directions ! You've been a huge help ❤️ ❤️ ❤️ ❤️ ❤️
