### ISSUE TITLE
[Bug]: Secret never Sync 

### ISSUE THREAD

**Issue by daniel-maganto** [upbound/provider-aws#1128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

secretsmanager.aws.upbound.io/v1beta1 - Secret

### Resource MRs required to reproduce the bug

```
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: test-dmaganto1
spec:
  forProvider:
    name: test-dmaganto1
    region: eu-central-1
    recoveryWindowInDays: 0
  providerConfigRef:
    name: aws-admin-my-account-upbound
```

### Steps to Reproduce

Apply this resource in the cluster

### What happened?

It never reach the state Sync: true

### Relevant Error Output Snippet

```shell
- lastTransitionTime: "2024-02-06T10:12:27Z"
    message: 'observe failed: cannot compute the instance diff: failed to compute
      the customized terraform.InstanceDiff: could not read replica block from config'
```

### Crossplane Version

1.14.5

### Provider Version

1.0.0

### Kubernetes Version

v1.28.2

### Kubernetes Distribution

EKS
