### ISSUE TITLE
[Bug]: `instance.rds.aws.upbound.io/v1beta2` Created with a default name

### ISSUE THREAD

**Issue by cest-pas-faux** [upbound/provider-aws#1138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* rds.aws.upbound.io/v1beta2 - Instance

### Resource MRs required to reproduce the bug

```yaml
apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  name: name-issue
spec:
  deletionPolicy: Delete
  forProvider:
    allocatedStorage: 100
    allowMajorVersionUpgrade: true
    applyImmediately: true
    autoMinorVersionUpgrade: false
    backupRetentionPeriod: 1
    copyTagsToSnapshot: true
    dbName: mydb
    dbSubnetGroupNameRef:
      name: REPLACEME
    engine: mysql
    engineVersion: 8.0.35
    instanceClass: db.t3.micro
    passwordSecretRef:
      key: password
      name: name-issue
      namespace: default
    region: us-east-1
    skipFinalSnapshot: true
    storageEncrypted: true
    username: root
    vpcSecurityGroupIdRefs:
    - name: REPLACEME
  managementPolicies:
  - '*'
  providerConfigRef:
    name: providerconfig-family-aws
  publishConnectionDetailsTo:
    configRef:
      name: default
    name: name-issue

```

### Steps to Reproduce

- Apply the provided manifest
- Check AWS console

### What happened?

- Name in the AWS console is not what we should expect
![image](https://github.com/upbound/provider-aws/assets/23448243/c153266a-2d39-4352-b698-37009c530a8e)

### Relevant Error Output Snippet

```shell
Output trimmed for clarity

apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  name: testalex-rdsinstance-r74cm
spec:
  deletionPolicy: Delete
  forProvider:
    allocatedStorage: 100
    applyImmediately: true
    autoMinorVersionUpgrade: true
    availabilityZone: us-east-1d
    backupRetentionPeriod: 1
    backupWindow: 06:16-06:46
    caCertIdentifier: rds-ca-rsa2048-g1
    dbName: mydb
    dbSubnetGroupName: default-rds-eks77-tst-us-east-1
    dbSubnetGroupNameRef:
      name: default-rds-eks77-tst-us-east-1
    deleteAutomatedBackups: true
    engine: mysql
    engineVersion: 8.0.35
    instanceClass: db.t3.micro
    licenseModel: general-public-license
    maintenanceWindow: thu:08:20-thu:08:50
    networkType: IPV4
    optionGroupName: default:mysql-8-0
    parameterGroupName: default.mysql8.0
    passwordSecretRef:
      key: password
      name: testalex-rdsinstance
      namespace: testalex
    port: 3306
    region: us-east-1
    skipFinalSnapshot: true
    storageType: gp2
    username: root
    vpcSecurityGroupIdRefs:
    - name: default-rds-eks77-tst-us-east-1
    vpcSecurityGroupIds:
    - sg-01caf7e64553aef3d
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: providerconfig-family-aws
  publishConnectionDetailsTo:
    configRef:
      name: default
    name: testalex-rdsinstance-r74cm
status:
  atProvider:
    address: terraform-20240207150854356000000001.cmcypbsqbicb.us-east-1.rds.amazonaws.com
    allocatedStorage: 100
    applyImmediately: true
    arn: arn:aws:rds:us-east-1:134842860454:db:terraform-20240207150854356000000001
    autoMinorVersionUpgrade: true
    availabilityZone: us-east-1d
    backupRetentionPeriod: 1
    backupWindow: 06:16-06:46
    caCertIdentifier: rds-ca-rsa2048-g1
    characterSetName: ""
    copyTagsToSnapshot: false
    customIamInstanceProfile: ""
    customerOwnedIpEnabled: false
    dbName: mydb
    dbSubnetGroupName: default-rds-eks77-tst-us-east-1
    deleteAutomatedBackups: true
    deletionProtection: false
    domain: ""
    domainIamRoleName: ""
    endpoint: terraform-20240207150854356000000001.cmcypbsqbicb.us-east-1.rds.amazonaws.com:3306
    engine: mysql
    engineVersion: 8.0.35
    engineVersionActual: 8.0.35
    hostedZoneId: Z2R2ITUGPM61AM
    iamDatabaseAuthenticationEnabled: false
    id: db-GKFPAKWSRGYQYCFOG4KXPJQJRU
    instanceClass: db.t3.micro
    iops: 0
    kmsKeyId: ""
    latestRestorableTime: "2024-02-07T15:13:49Z"
    licenseModel: general-public-license
    maintenanceWindow: thu:08:20-thu:08:50
    maxAllocatedStorage: 0
    monitoringInterval: 0
    monitoringRoleArn: ""
    multiAz: false
    ncharCharacterSetName: ""
    networkType: IPV4
    optionGroupName: default:mysql-8-0
    parameterGroupName: default.mysql8.0
    performanceInsightsEnabled: false
    performanceInsightsKmsKeyId: ""
    performanceInsightsRetentionPeriod: 0
    port: 3306
    publiclyAccessible: false
    replicaMode: ""
    replicateSourceDb: ""
    resourceId: db-GKFPAKWSRGYQYCFOG4KXPJQJRU
    skipFinalSnapshot: true
    status: available
    storageEncrypted: false
    storageThroughput: 0
    storageType: gp2
    timezone: ""
    username: root
    vpcSecurityGroupIds:
    - sg-01caf7e64553aef3d
  conditions:
  - lastTransitionTime: "2024-02-07T15:17:55Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-02-07T15:08:54Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-02-07T15:17:54Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
```

### Crossplane Version

1.14.2-up.1

### Provider Version

1.0.0

### Kubernetes Version

1.26

### Kubernetes Distribution

EKS

**Comment by ulucinar** [comment]
With the introduction of the `v1beta2` API version, there's a [configuration change for this resource](https://github.com/upbound/provider-aws/releases/tag/v1.0.0?api_changes) in the `v1.0.0` version of the provider. You now need to specify the database identifier as follows:
```yaml
piVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  name: name-issue
spec:
  deletionPolicy: Delete
  forProvider:
    dbName: mydb
    identifier: testidentifier
...
```
, which results in the given identifier being assigned to the provisioned database:
<img width="312" alt="image" src="https://github.com/upbound/provider-aws/assets/9376684/5d056833-df86-420e-931e-dd792caba23b">

Could you please add the `spec.forProvider.identifier` parameter to your manifest?
