### ISSUE TITLE
[Bug]: Cannot create RDS cluster using serverlessv2Scaling: `InvalidParameterValue: Both MinCapacity and MaxCapacity must be specified when you initialize Serverless v2 scaling configuration.`

### ISSUE THREAD

**Issue by cloudymax** [upbound/provider-aws#1165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

rds.aws.upbound.io/v1beta1 - Cluster

### Resource MRs required to reproduce the bug

```yaml
---
# Source: crossplane/templates/rds-cluster.yaml
apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: my-rds-cluster
  namespace: crossplane-system
spec:
  forProvider:
    engine: aurora-mysql
    enabledCloudwatchLogsExports:
      - audit
      - general
      - error
    engineVersion: 8.0.mysql_aurora.3.03.1
    engineMode: provisioned
    serverlessv2ScalingConfiguration:
      - minCapacity: 1
      - maxCapacity: 4
    masterPasswordSecretRef:
      key: password
      name: xxxxxx-rds-password
      namespace: crossplane-system
    masterUsername: admin
    region: eu-xxxx-x
    skipFinalSnapshot: true
    dbSubnetGroupName: subnet-group
    vpcSecurityGroupIds:
      - sg-xxxxxxxxxxxxxx
    storageEncrypted: true
  providerConfigRef:
    name: xxx-xxx-xxx-dev
  writeConnectionSecretToRef:
    name: rds-cluster-secret
    namespace: crossplane-system
```

### Steps to Reproduce

create an RDS cluster using the configuration outlined above (using your own security groups etc... of course)

Verify that the min and max capacity settings are indeed set, but the error is shown anyway

```console
> kd cluster
Name:         my-rds-cluster
Namespace:
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2024-02-19T15:17:15Z
              crossplane.io/external-create-succeeded: 2024-02-19T15:17:15Z
              crossplane.io/external-name: my-rds-cluster
              meta.upbound.io/example-id: rds/v1beta1/cluster
API Version:  rds.aws.upbound.io/v1beta1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2024-02-19T15:14:27Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:        3
  Resource Version:  6489753
  UID:               -
Spec:
  Deletion Policy:  Delete
  For Provider:
    Db Subnet Group Name:  -
    Enabled Cloudwatch Logs Exports:
      audit
      general
      error
    Engine:          aurora-mysql
    Engine Mode:     provisioned
    Engine Version:  8.0.mysql_aurora.3.03.1
    Master Password Secret Ref:
      Key:            password
      Name:           -
      Namespace:      crossplane-system
    Master Username:  -
    Region:           -
    serverlessv2ScalingConfiguration: <----------------------------- options are set
      Min Capacity:       1
      Max Capacity:       4
    Skip Final Snapshot:  true
    Storage Encrypted:    true
    Tags:
      Crossplane - Kind:            cluster.rds.aws.upbound.io
      Crossplane - Name:            my-rds-cluster
      Crossplane - Providerconfig:  sie-cloud-horizononline-dev
    Vpc Security Group Ids:
      sg----------------
  Init Provider:
  Management Policies:
    *
  Provider Config Ref:
    Name: -
  Write Connection Secret To Ref:
    Name:       rds-cluster-secret
    Namespace:  crossplane-system
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2024-02-19T15:14:27Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2024-02-19T15:14:27Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2024-02-19T15:17:15Z
    Message:               async create failed: failed to create the resource: [{0 creating RDS Cluster (my-rds-cluster): InvalidParameterValue: Both MinCapacity and MaxCapacity must be specified when you initialize Serverless v2 scaling configuration. 
status code: 400, request id: d6907b42-473f-4d21-8e4c-388773fa079f <------------------------------- still get the error
 []}]
    Reason:                AsyncCreateFailure
    Status:                False
    Type:                  LastAsyncOperation
Events:
  Type    Reason                   Age                   From
             Message
  ----    ------                   ----                  ----
             -------
  Normal  PendingExternalResource  47s (x16 over 3m17s)  managed/rds.aws.upbound.io/v1beta1, kind=cluster  Waiting for external resource existence to be confirmed
  Normal  CreatedExternalResource  30s (x6 over 3m18s)   managed/rds.aws.upbound.io/v1beta1, kind=cluster  Successfully requested creation of external resource
```

### What happened?

Get the following error

```console
async create failed: failed to create the resource: [{0 creating RDS Cluster (my-rds-cluster): InvalidParameterValue: Both MinCapacity and MaxCapacity must be specified when you initialize Serverless v2 scaling configuration.
```

### Relevant Error Output Snippet

```shell
Message:               async create failed: failed to create the resource: [{0 creating RDS Cluster (my-rds-cluster): InvalidParameterValue: Both MinCapacity and MaxCapacity must be specified when you initialize Serverless v2 scaling configuration. 
status code: 400, request id: d6907b42-473f-4d21-8e4c-388773fa079f
```

### Crossplane Version

1.14.5

### Provider Version

1.0.0

### Kubernetes Version

Server Version: v1.28.5-eks-5e0fdde

### Kubernetes Distribution

EKS
