### ISSUE TITLE
Configuration error while testing aws_cloudwatch_log_destination: kinesis_for_cloudwatch is generated successfully, but aws_cloudwatch_log_destination can't define it

### ISSUE THREAD

**Issue by svscheg** [upbound/provider-aws#117]
### What happened?

During testing the resource aws_cloudwatch_log_destination we have heve a configuration error  - aws_kinesis_stream.kinesis_for_cloudwatch is generated successfully, but aws_cloudwatch_log_destination can't define it
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_destination

resource "aws_cloudwatch_log_destination" "test_destination" {
  name       = "test_destination"
  role_arn   = aws_iam_role.iam_for_cloudwatch.arn
  target_arn = aws_kinesis_stream.kinesis_for_cloudwatch.arn
}

Error:
message: 'cannot resolve references: mg.Spec.ForProvider.TargetArn: referenced
      field was empty (referenced resource may not yet be ready)'
    reason: ReconcileError
    status: "False"
    type: Synced

This issue relates to https://github.com/upbound/provider-aws/issues/46

Related files:
[yaml_outputof_kinesis.txt](https://github.com/upbound/provider-aws/files/9921431/yaml_outputof_kinesis.txt)
[yaml_outputof_destination.txt](https://github.com/upbound/provider-aws/files/9921433/yaml_outputof_destination.txt)
[destination.yaml.txt](https://github.com/upbound/provider-aws/files/9921441/destination.yaml.txt)

### How can we reproduce it?

Copy generated manifest, add missing dependancy iam_for_cloudwatch and kinesis_for_cloudwatch, try to apply manifest.

The following manifests can be used to reproduce the issue:

```yaml
apiVersion: cloudwatchlogs.aws.upbound.io/v1beta1
kind: Destination
metadata:
  annotations:
    meta.upbound.io/example-id: cloudwatchlogs/v1beta1/destination
  labels:
    testing.upbound.io/example-name: test_destination
  name: test-destination
spec:
  forProvider:
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: iam_for_cloudwatch
    targetArnSelector:
      matchLabels:
        testing.upbound.io/example-name: kinesis_for_cloudwatch

---

apiVersion: kinesis.aws.upbound.io/v1beta1
kind: Stream
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "This resource is a dependency of Destination, which needs manual intervention."
  labels:
    testing.upbound.io/example-name: kinesis_for_cloudwatch
  name: example
spec:
  forProvider:
    region: us-west-1
    shardCount: 1

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "This resource is a dependency of Destination, which needs manual intervention."
  name: sample-role
  labels:
    testing.upbound.io/example-name: iam_for_cloudwatch
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "cloudwatch.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
```

### What environment did it happen in?

* Universal Crossplane Version:
* Provider Version:
