### ISSUE TITLE
[Bug]: ECR provider doesn't support -- in the repo name

### ISSUE THREAD

**Issue by dhumphries-sainsburys** [upbound/provider-aws#1179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

ecr.aws.upbound.io/v1beta1 - Repository

### Resource MRs required to reproduce the bug

```
apiVersion: ecr.aws.upbound.io/v1beta1
kind: Repository
metadata:
  name: test-dan-humphries--hello-bosun
spec:
  deletionPolicy: Orphan
  forProvider:
    imageScanningConfiguration:
      - scanOnPush: true
    imageTagMutability: IMMUTABLE
    region: eu-west-1
  providerConfigRef:
    name: aws-upbound
```

### Steps to Reproduce

1) Create the example manifest
2) See errors like so in status field
```
observe failed: failed to observe the resource: [{0 reading ECR
        Repository (test-dan-humphries--hello-bosun):
        InvalidParameterException: Invalid parameter at 'repositoryName' failed
        to satisfy constraint: 'must satisfy regular expression
        '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''  []}]
```

### What happened?

This is a perfectly valid repository name that we have created using the community aws crossplane provider that we would adopt using the upbound one (and create further ones too). I would expect whatever regex it is using to check the name to be in line with the actual restrictions in AWS. You get the same error even using `crossplane.io/external-name` which is often recommended as the way to get around issues with k8s name restrictions not being aligned with AWS name restrictions (neither of which this falls afoul of anyways)

### Relevant Error Output Snippet

```shell
observe failed: failed to observe the resource: [{0 reading ECR
        Repository (test-dan-humphries--hello-bosun):
        InvalidParameterException: Invalid parameter at 'repositoryName' failed
        to satisfy constraint: 'must satisfy regular expression
        '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''  []}]
```

### Crossplane Version

1.13.2

### Provider Version

1.1.0

### Kubernetes Version

1.28

### Kubernetes Distribution

EKS
