### ISSUE TITLE
[Bug]: `newerNoncurrentVersions` will result in XML not well-formed error

### ISSUE THREAD

**Issue by schaschko** [upbound/provider-aws#1731]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

s3.aws.upbound.io/v1beta1 - BucketLifecycleConfiguration

### Resource MRs required to reproduce the bug

```yaml
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketLifecycleConfiguration
metadata:
  name: my-bucket-lifecycle-conf
spec:
  forProvider:
    bucketRef:
      name: my-bucket
    region: my-region
    rule:
      - noncurrentVersionExpiration:
          - noncurrentDays: 1
            # `newerNoncurrentVersions` will result in an error
            newerNoncurrentVersions: "2"
        status: Enabled
        id: non-current-version-expiration
  providerConfigRef:
    name: my-providerconfig
```

### Steps to Reproduce

Apply the resource MR as defined above.

### What happened?

It will result in XML error, see below.

Some issues point in the direction that it would be required to manually set in the `rule` array:

```
        filter:
          - prefix: ""
```

but it's automatically set by the provider.

If `newerNoncurrentVersions: "2"` is removed, everything works. Can you please look into that?

### Relevant Error Output Snippet

```shell
    message: 'async create failed: failed to create the resource: [{0 creating S3
      Bucket (my-bucket) Lifecycle Configuration: operation error S3:
      PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID:
      ..., HostID: ...,
      api error MalformedXML: The XML you provided was not well-formed or did not
      validate against our published schema  []}]'
```

### Crossplane Version

1.18.2

### Provider Version

1.19.0
