### ISSUE TITLE
[Bug]: SES `DomainDKIM` doesn't generate `dkimTokens`

### ISSUE THREAD

**Issue by arturkasperek** [upbound/provider-aws#1796]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

* ses.aws.upbound.io/v1beta1 - DomainDKIM

### Steps to Reproduce

Create resurces like here:
```yaml
apiVersion: ses.aws.upbound.io/v1beta1
kind: DomainIdentity
metadata:
  annotations:
    crossplane.io/external-name: test.foo.com
  name: test-r9st8
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: test
```
and
```yaml
apiVersion: ses.aws.upbound.io/v1beta1
kind: DomainDKIM
metadata:
  annotations:
    crossplane.io/external-name: test.foo.com
  name: test-dvxww
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: test
```

### What happened?

After creating the above resources I see in status only ID:
```yaml
...
status:
  atProvider:
    id: test.foo.com
```
We are missing `dkimTokens`.

I noticed that after going into the AWS UI and clicking this button:

<img width="1603" alt="Image" src="https://github.com/user-attachments/assets/80694e56-d8a6-4031-be27-ff09e0bd0e6d" />
things started to work correctly and `dkimTokens` field was set by crossplane correctly.

I think  `kind: DomainDKIM` should make sure to generate those keys without human manual step

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

v1.19.0-up.1

### Provider Version

v1.22.0

### Kubernetes Version

v1.30.11-eks-bcf3d70

### Kubernetes Distribution

EKS
