### ISSUE TITLE
[Bug]: Crossplane V2 preview fails to resolve matching by name reference (<KIND>IdRef) for modular provider resources (aws.m.upbound.io)

### ISSUE THREAD

**Issue by Heniland** [upbound/provider-aws#1804]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

*.aws.m.upbound.io/v1beta1

### Resource MRs required to reproduce the bug

```
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws-config-dev
spec:
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<YOUR_ROLE_NAME>
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2:v1.22.0-crossplane-v2-preview.0
  revisionHistoryLimit: 5
  runtimeConfigRef:
    name: aws-config-dev
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: crossplane-dev-provider-config
spec:
  credentials:
    source: IRSA
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPC
metadata:
  name: dev-01-vpc-reused
  namespace: crossplane
  annotations:
    crossplane.io/external-name: vpc-0a123456789012345 # Replace with your actual VPC ID
spec:
  forProvider:
    region: eu-central-1 # Replace with your actual region
  providerConfigRef:
    name: crossplane-dev-provider-config
  managementPolicies:
    - Observe
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: cp-web-server-test-sg
  namespace: crossplane
spec:
  forProvider:
    region: eu-central-1 # Replace with your actual region
    name: cp-web-server-test-sg
    description: "Allow HTTPS traffic for web servers."
    vpcIdRef: # <---------------------------------- PROBLEM: This is not working
      name: dev-01-vpc-reused
    tags:
      Name: "cp-web-server-test-sg"
  providerConfigRef:
    name: crossplane-dev-provider-config
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroupIngressRule
metadata:
  name: cp-web-server-test-sg-https-ingress
  namespace: crossplane
spec:
  forProvider:
    region: eu-central-1 # Replace with your actual region
    securityGroupIdRef: # <---------------------------------- PROBLEM: This is not working
      name: cp-web-server-test-sg
    fromPort: 443
    toPort: 443
    protocol: "tcp"
    cidrBlocks:
      - "0.0.0.0/0"
  providerConfigRef:
    name: crossplane-dev-provider-config
```

### Steps to Reproduce

> Assuming you have installed xpkg.crossplane.io/crossplane/crossplane:v2.0.0-preview.1

To reproduce this issue, apply the YAML manifests as detailed in the steps above.

### What happened?

The bug appears to be a general failure of the name-based reference resolution mechanism whenever a resource from the aws.m.upbound.io API group tries to reference another resource from the same modular family.

The examples in this report specifically demonstrate this failure with **vpcIdRef** on a SecurityGroup and **securityGroupIdRef** on a SecurityGroupIngressRule. 

We expect this issue affects all similar cross-resource references within the v1.22.0-crossplane-v2-preview.0 provider packages.

### Relevant Error Output Snippet

```shell
cannot resolve references: mg.Spec.ForProvider.VPCID: cannot get referenced resource: VPC.ec2.aws.upbound.io "dev-01-vpc-reused" not found

Note: VPC is defined using VPC.ec2.aws.m.upbound.io but it looking for VPC.ec2.aws.upbound.io

kubectl get vpc --all-namespaces
NAMESPACE    NAME                SYNCED   READY   EXTERNAL-NAME           AGE
crossplane   dev-01-vpc-reused   True     True    vpc-0a123456789012345   45m
```

### Crossplane Version

v2.0.0-preview.1

### Provider Version

v1.22.0-crossplane-v2-preview.0

### Kubernetes Version

Client Version: v1.32.2 Kustomize Version: v5.5.0 Server Version: v1.32.3-eks-4096722

### Kubernetes Distribution

EKS

### Additional Info

There is a similar request at https://github.com/crossplane-contrib/provider-upjet-aws/issues/1798 but I created a bug report to give more details.
