### ISSUE TITLE
[Bug]: AWS Route53 records fail to update when values change

### ISSUE THREAD

**Issue by cbmachinify** [upbound/provider-aws#1806]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

* route53.aws.upbound.io/v1beta2 - Record

### Resource MRs required to reproduce the bug

```
apiVersion: route53.aws.upbound.io/v1beta2
kind: Record
metadata:
  name: a-test.fake.domain
spec:
  managementPolicies:
    - Create
    - Update
    - Delete
    - LateInitialize
    - Observe
  forProvider:
    name: test
    region: us-east-1
    type: TXT
    zoneId: Z1234356789
    ttl: 300
    records:
      - test message
```

### Steps to Reproduce

* Create a record
* Try to update record

### What happened?

When changing a record value, sync fails with the error provided in **Relevent Error Output Snippet**. Not just TXT records, but A records as well. Might be more.
```
# FROM
    records:
      - test message
# TO
    records:
      - test message 2
```

### Relevant Error Output Snippet

```shell
- lastTransitionTime: "2025-06-16T19:07:30Z"
    message: 'async update failed: failed to update the resource: [{0 creating Route53
      Record: operation error Route 53: ChangeResourceRecordSets, https response error
      StatusCode: 400, RequestID: xxxxxxxxxxxxxxxxxxx, InvalidInput:
      Invalid request: Expected exactly one of [AliasTarget, all of [TTL, and ResourceRecords],
      or TrafficPolicyInstanceId], but found none in Change with [Action=UPSERT, Name=test.fake.domain,
      Type=TXT, SetIdentifier=null]  []}]'
    reason: AsyncUpdateFailure
    status: "False"
    type: LastAsyncOperation
```

### Crossplane Version

1.17.0

### Provider Version

1.22.0

### Kubernetes Version

v1.32.3-eks-4096722

### Kubernetes Distribution

AWS EKS
