### ISSUE TITLE
ControllerConfig: --enable-external-secret-stores causing provider pod crash

### ISSUE THREAD

**Issue by satishweb** [upbound/provider-aws#205]
### What happened?
Provider installation is successful but pod keep crashing because of the below error:
```
[ MAC ]: kubectl logs -f crossplane-provider-upbound-aws-c49e1af5e48d-57cc6845bb-dtxjs

1.6694477798672595e+09	DEBUG	provider-aws	Starting	{"sync-interval": "1h0m0s", "poll-interval": "10m0s", "max-reconcile-rate": 10}
I1126 07:29:40.888637       1 request.go:601] Waited for 1.005284477s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/codestarnotifications.aws.upbound.io/v1beta1?timeout=32s
1.66944778180706e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
1.669447784622781e+09	INFO	provider-aws	Alpha feature enabled	{"flag": "EnableAlphaExternalSecretStores"}
provider: error: cannot create default store config: no kind is registered for the type v1alpha1.StoreConfig in scheme "pkg/runtime/scheme.go:100"
```

### How can we reproduce it?
1. Deploy the provider using below specs:
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/crossplane-role-name
  name: crossplane-provider-upbound-aws
spec:
  args:
  - --debug
  - --enable-external-secret-stores
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-upbound-aws
spec:
  controllerConfigRef:
    name: crossplane-provider-upbound-aws
  ignoreCrossplaneConstraints: false
  package: xpkg.upbound.io/upbound/provider-aws:v0.21.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: crossplane-provider-upbound-aws
spec:
  credentials:
    source: IRSA
```
2. Wait for the provider pods to appear
3. Check the logs of the provider pod
4. Comment out the `--enable-external-secret-stores` in ControllerConfig. Pod does not crash after the new replica set is created by new config. 
### What environment did it happen in?

* Universal Crossplane Version: 1.10.1
* Provider Version: 0.21.0
