### ISSUE TITLE
Invalid security token when running against localstack

### ISSUE THREAD

**Issue by agermain** [upbound/provider-aws#206]
### What happened?

When running the provider against localstack, I'm seeing the following message:
```
cannot get terraform setup: cannot get the caller identity: GetCallerIdentity query failed: GetCallerIdentity query failed: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 821527d0-d6fa-441d-b5d3-a280b4767650, api error InvalidClientTokenId: The security token included in the request is invalid.
```

### How can we reproduce it?

1. Create a cluster with kind
2. Start localstack with `localstack start -d`
3. Connect localstack's container with `docker network connect kind localstack_main`
4. Install crossplane via Helm: `helm upgrade --install crossplane --create-namespace --namespace crossplane-system crossplane-stable/crossplane --wait > /dev/null 2>&1`
5. Create provider:
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: default
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v0.21.0
```
6. Get localstack's container IP via `docker inspect localstack_main | jq -r ".[].NetworkSettings.Networks[\"kind\"].IPAddress"`
7. Provision `ProviderConfig` with the IP from previous step:
```
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  endpoint:
    url:
      type: Static
      static: http://${LOCALSTACK_IP}:4566
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-creds
  namespace: crossplane-system
stringData:
  creds: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test
```
8. Provision some bucket:
```
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: upbound-example
  name: somebucket 
spec:
  forProvider:
    forceDestroy: true
    region: us-west-1
```

When trying this with [crossplane-contrib/provider-aws](https://github.com/crossplane-contrib/provider-aws), it works fine, which makes me think it might have to do with the provider itself. I can't see any request getting through to localstack either.

### What environment did it happen in?

* Universal Crossplane Version: N/A
* Provider Version: 0.21.0
