### ISSUE TITLE
iam: Role CRD is not working with ProviderConfig with assumeRoleChain

### ISSUE THREAD

**Issue by fcastarede** [upbound/provider-aws#215]
### What happened?

Creation of IAM Roles failed. It seems to be due to operation error STS (I use an IAM user assuming a role in other AWS account). The error message is:
"cannot get terraform setup: failed to retrieve aws credentials from aws config: failed to refresh cached credentials, operation error STS: AssumeRole, failed to resolve service endpoint, an AWS region is required, but was not found"

The others ressources in my composition are well created (VPC, Subnet, NATGateway, InternetGateway, etc...)

### How can we reproduce it?

ProviderConfig:
```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: test1
spec:
  assumeRoleChain:
    - roleARN: arn:aws:iam::22222222222:role/admin
  credentials:
    secretRef:
      key: creds
      name: aws-creds
      namespace: test1
    source: Secret
```

Role:
```yaml
 name: iamrole-controlplane
    base:
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: Role
      spec:
        forProvider:
          assumeRolePolicy: |
            {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Principal": {
                          "Service": [
                              "eks.amazonaws.com"
                          ]
                      },
                      "Action": [
                          "sts:AssumeRole"
                      ]
                  }
              ]
            }
    patches:
    - type: PatchSet
      patchSetName: providerconfigref
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: '%s-controlplane'
    - fromFieldPath: spec.id
      toFieldPath: metadata.labels.role
      transforms:
      - type: string
        string:
          fmt: '%s-controlplane'
```

### What environment did it happen in?

* Universal Crossplane Version: 1.10.1-up.1
* Provider Version: xpkg.upbound.io/upbound/provider-aws:v0.21.0
* kubectl version: 1.22.5
* Kubernetes version: docker-desktop Kubernetes v1.22.5
* OS: macOS 12.6 Monterey

**Comment by blakebarnett** [comment]
I'm seeing a similar issue, but it seems to apply to any resources.

We see:
```
  Warning  CannotObserveExternalResource    22s (x63 over 4m48s)   managed/s3.aws.upbound.io/v1beta1, kind=bucket  (combined from similar events): cannot run refresh: refresh failed: error reading S3 Bucket (test-bucket-foo): BadRequest: Bad Request
           status code: 400, request id: <redacted>, host id: <redacted>:
```

I've verified that this only happens when attempting to use `assumeRoleChain`, IRSA for the account that provider-aws is running in is working. Creating the same test bucket resource works as expected.

**Comment by fcastarede** [comment]
This issue occurs for the resources of the IAM API, but for EC2 there is no problem with `assumeRoleChain`

**Comment by ctkeyser** [comment]
I'm seeing the same issue. I think this happens because the STS service [requires a region](https://github.com/aws/aws-sdk-go-v2/blob/3cc55fe104963aa9bf66559f9ca5c5bb2f96df02/service/sts/api_client.go#L92-L93), but the IAM managed resources don't require a region. [This](https://github.com/upbound/provider-aws/blob/5f0ace90a32ed716ba9cfea2acb48de176b3442c/internal/clients/provider_config.go#L76) is where the region is pulled from the managed resource, and there doesn't seem to be a way to define a default region to fall back to, or a way to define an region specifically for STS requests. Maybe could add an AssumeRoleSTSRegion option to the ProviderConfig and prefer that, and fall back to managed resource region if that isn't set

**Comment by ulucinar** [comment]
I have also reproduced this issue with an STS role chaining configuration. I was able to successfully provision a VPC but failed to provision an IAM Role with the following `ProviderConfig`:
```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: aws-creds
      key: creds
  assumeRoleChain:
    - roleARN: arn:aws:iam::<account>:role/alper-rc-1
    - roleARN: arn:aws:iam::<account>:role/alper-rc-2
```

```shell
❯ k get managed
NAME                                READY   SYNCED   EXTERNAL-NAME           AGE
vpc.ec2.aws.upbound.io/sample-vpc   True    True     ...   163m

NAME                                        READY   SYNCED   EXTERNAL-NAME       AGE
role.iam.aws.upbound.io/sample-role-alper           False    ...   163m
```
