### ISSUE TITLE
ec2: `SecurityGroupRule` is not working when `spec.forProvider.self` is set to `true`

### ISSUE THREAD

**Issue by ytsarev** [upbound/provider-aws#228]
### What happened?

When `spec.forProvider.self` is set to `true` we hit 

```
  Warning  CannotObserveExternalResource    1s (x3 over 3s)    managed/ec2.aws.upbound.io/v1beta1, kind=securitygrouprule  cannot run refresh: refresh failed: Conflicting configuration arguments: "self": conflicts with source_security_group_id
```

### How can we reproduce it?

```
cat example.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: sample-vpc
spec:
  forProvider:
    cidrBlock: 172.16.0.0/16
    region: us-east-1
    tags:
      Name: DemoVpc

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    selector: here-i-am
  name: test-vpc
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: sample-vpc

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: test-vpc-securitygroup
spec:
  deletionPolicy: Delete
  forProvider:
    fromPort: 22
    protocol: tcp
    region: us-east-1
    securityGroupIdSelector:
      matchLabels:
        selector: here-i-am
    self: true
    toPort: 22
    type: ingress
```

```
kubectl apply -f example.yaml
```

```
kubectl describe securitygrouprule.ec2.aws.upbound.io/test-vpc-securitygroup
....
  Warning  CannotObserveExternalResource    84s (x4 over 102s)     managed/ec2.aws.upbound.io/v1beta1, kind=securitygrouprule  cannot run refresh: refresh failed: Conflicting configuration arguments: "source_security_group_id": conflicts with self
Conflicting configuration arguments: "self": conflicts with source_security_group_id
```

### What environment did it happen in?

* Universal Crossplane Version: universal-crossplane-1.9.1-up.2
* Provider Version: xpkg.upbound.io/upbound/provider-aws:v0.21.0
