### ISSUE TITLE
aws.rds: `Alias` on aws kms failing on 0.7.0

### ISSUE THREAD

**Issue by AaronME** [upbound/provider-aws#24]
### What happened?
When attempting to create a KMS alias on aws using official provider we saw the following error message:
```yaml
  atProvider: {}
  conditions:
    - lastTransitionTime: '2022-08-12T16:27:51Z'
      message: >-
        observe failed: cannot run refresh: refresh failed: "name" must begin
        with 'alias/' and be comprised of only [a-zA-Z0-9/_-]: : File name:
        main.tf.json
      reason: ReconcileError
      status: 'False'
      type: Synced

```

### How can we reproduce it?
We used the following manifests:

```yaml
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
  name: official-provider-google
spec:
  forProvider:
    region: us-west-2
    description: Key For Testing containeraws.gcp.upbound.io resources
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Alias
metadata:
  name: official-provider-google
spec:
  forProvider:
    region: us-west-2
    targetKeyIdRef:
      name: official-provider-google
```

### What environment did it happen in?

* Crossplane Version: 1.9.0-up.2
* Provider Name: upbound/provider-aws
* Provider Version: v0.7.0
