### ISSUE TITLE
s3: `Bucket` CRD is not working (ProviderConfig not being used?)

### ISSUE THREAD

**Issue by danielloader** [upbound/provider-aws#383]
### What happened?

Attempted to deploy a bucket in localstack, running in the same namespace for simplicity. 

Bucket fails to get created as the `GetCallerIdentity` call is going to actual AWS servers in `us-east-1` rather than to localstack inside the cluster.

Error event on the bucket CRD:

```
cannot get terraform setup: cannot get the caller identity: GetCallerIdentity query failed: GetCallerIdentity query failed: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 93da9bff-cc1a-4d17-aa09-79e71f426607, api error InvalidClientTokenId: The security token included in the request is invalid.
```

Included a copy of the relevant ProviderConfig that doesn't seem to be working: (rest of the manifests are in the linked repo)

```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-aws-upbound
  namespace: crossplane
spec:
  endpoint:
    hostnameImmutable: true
    url: 
      type: Static
      static: http://crossplane-localstack:4566
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: aws-secret
      key: creds
```

Would expect the AWS SDK calls to go to localstacks service endpoint rather than AWS, like the community AWS provider; confirmed it's doing TLS calls out to AWS via termshark pod on the host network.

### How can we reproduce it?

Compiled some kubernetes manifests to reproduce the issue here:
https://github.com/danielloader/upbound-localstack-issue

The repo uses fluxCD controller to deploy the helm charts, but the following should work without it:

```bash
$ helm repo add localstack https://localstack.github.io/helm-charts
$ helm install crossplane-localstack localstack/localstack --namespace crossplane --create-namespace
```

```bash
helm repo add crossplane-stable https://charts.crossplane.io/stable
helm repo update
helm install crossplane --namespace crossplane crossplane-stable/crossplane
```

### What environment did it happen in?

* Universal Crossplane Version: Upstream Crossplane 1.10.1 (stable)
* Provider Version: 0.24
* Kubernetes Version: 1.25.4
* Kubernetes Distribution: k3s
* OS: Running Rancher Desktop on Mac.
