### ISSUE TITLE
cloudwatch: `MetricAlarm` does not match aws spec

### ISSUE THREAD

**Issue by AaronME** [upbound/provider-aws#408]
### What happened?
[MetricAlarm](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.25.0/resources/cloudwatch.aws.upbound.io/MetricAlarm/v1beta1) is defining [dimensions](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.25.0/resources/cloudwatch.aws.upbound.io/MetricAlarm/v1beta1#doc:spec-forProvider-dimensions) as an object.

The AWS [documentation](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-alarm.html) defines this as a list of objects, allowing for multiple dimensions.

Attempting to declare multiple dimensions results in the error:

```shell
error validating data: ValidationError(MetricAlarm.spec.forProvider.dimensions): invalid type for io.upbound.aws.cloudwatch.v1beta1.MetricAlarm.spec.forProvider.dimensions: got "array", expected "map";
```

### How can we reproduce it?
Attempt to apply a MetricAlarm like the following:

```yaml
apiVersion: cloudwatch.aws.upbound.io/v1beta1
kind: MetricAlarm
metadata:
  name: mastodon-alb-targets-5xx-status
spec:
  forProvider:
    alarmActions: [
      "arn:aws:sns:us-west-1:123456789012:testing"
    ]
    alarmDescription: Application load balancer receives 5XX HTTP status codes from targets
    comparisonOperator: GreaterThanThreshold
    metricName: HTTPCode_Target_5XX_Count
    namespace: AWS/ApplicationELB
    statistic: Sum
    period: 60
    evaluationPeriods: 1
    region: us-east-1
    threshold: 0
    dimensions:
      - name: LoadBalancer
        value: testing
      - name: TargetGroup
        value: testing
    treatMissingData: notBreaching
```

### What environment did it happen in?

* Universal Crossplane Version: v1.10.1-up.1
* Provider Version: v0.25.0

**Comment by ulucinar** [comment]
Hi @AaronME,
Thank you for reporting this issue. Checked the native schema of the `aws_cloudwatch_metric_alarm` resource [here](https://github.com/hashicorp/terraform-provider-aws/blob/23e60ef9a2151035df4204167b75ba052ca1f066/internal/service/cloudwatch/metric_alarm.go#L210), which is generated as a map [in the provider](https://github.com/upbound/provider-aws/blob/d1f9ce409cf80896cdcdfb50bc1f8f94fb56787e/apis/cloudwatch/v1beta1/zz_metricalarm_types.go#L52).

I think we need to do something like:
```yaml
apiVersion: cloudwatch.aws.upbound.io/v1beta1
kind: MetricAlarm
spec:
  forProvider:
    ...
    dimensions:
      LoadBalancer: testing
      TargetGroup: testing
```

Could you please give this a try?
