### ISSUE TITLE
ec2: `TransitGatewayRouteTablePropagation` CRD attachmentId and routeTableId seems inverted

### ISSUE THREAD

**Issue by AlexDouze** [upbound/provider-aws#434]
### What happened?
Impossible to create `TransitGatewayRouteTablePropagation` by referencing the `transitGatewayAttachmentId` and `transitGatewayRouteTableId`. Even with `IdRef` or `IdSelector`

The referencing ids look inverted somewhere.

### How can we reproduce it?

Create a `TransitGatewayRouteTablePropagation`:
```yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: TransitGatewayRouteTablePropagation
metadata:
  name: example
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-west-3
    #Ids are faked here
    transitGatewayAttachmentId: tgw-attach-1234567890
    transitGatewayRouteTableId: tgw-rtb-0987654321
  providerConfigRef:
    name: my-provider
```
The provider publishes a status condition:
```yaml
status:
  atProvider: {}
  conditions:
    - lastTransitionTime: '2023-01-10T16:22:04Z'
      #Ids are faked here
      message: "observe failed: cannot run refresh: refresh failed: error reading EC2 Transit Gateway Route Table (tgw-attach-1234567890) Propagation (tgw-rtb-0987654321): InvalidRouteTableId.Malformed: Invalid Transit Gateway Route Table id tgw-attach-1234567890.\n\tstatus code: 400, request id: xxxxx: "
      reason: ReconcileError
      status: 'False'
      type: Synced
```
Indeed tgw-attach-1234567890 is not a RouteTableId, but the attachement Id.
This is why I suspect some inverted Ids.

### What environment did it happen in?

* Universal Crossplane Version: v1.10.1-up.1
* Provider Version: v0.26.0
* Kubernetes Version: v1.24.8-eks-ffeb93d
* Kubernetes Distribution: EKS
* OS: amazon-eks-node-1.24-v20221222 (ami-071898f4f55a510e5) EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.24.7, docker: 20.10.17-1.amzn2.0.1, containerd: 1.6.6-1.amzn2.0.2)
