### ISSUE TITLE
Pegged CPU with v0.27.0 when applying a ProviderConfig

### ISSUE THREAD

**Issue by plumbis** [upbound/provider-aws#452]
### What happened?
When applying a "simple" ProviderConfig the CPU on the kube-apiserver goes to 100% on all cores and stays for at least 5 minutes. 

I can recreate this and sometimes it resolves and other times I'm locked out of my server until I reboot. 

### How can we reproduce it?
3-node Kubernetes cluster installed with kubeadm. 

I use Vagrant with KVM+Libvirt to stand up the base cluster. The full Vagrantfile is here: https://github.com/upbound/docs/blob/main/utils/vagrant/Vagrantfile

1. Install Crossplane:
```
helm repo add \
crossplane-stable https://charts.crossplane.io/stable
helm repo update

helm install crossplane \
crossplane-stable/crossplane \
--namespace crossplane-system \
--create-namespace
```

2. Create the provider
```
cat <<EOF | kubectl apply -f -
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v0.27.0
EOF
```

3. Create a secret key (contents don't matter) as `aws-credentials.txt`
```
[default]
aws_access_key_id = <aws_access_key>
aws_secret_access_key = <aws_secret_key>
```

4. Apply a ProviderConfig
```

cat <<EOF | kubectl apply -f -
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds
EOF
```

At this point CPU immediately goes to 100%. I've seen both `kubelet`, `etcd` and `kube-apiserver` processes consuming all of the CPU.

This `htop` output is from the APIServer (where the commands are being run) before the system locked and my SSH sessions died.
![Screen Shot 2023-01-17 at 12 00 51 PM](https://user-images.githubusercontent.com/10537576/212966015-8fd45e61-8272-4ac8-b1d4-f7d53dfe97b4.png)

### What environment did it happen in?

* Universal Crossplane Version: v1.10.1
* Provider Version: v0.27.0
* API Server:
    * 4 vCPUs (on 32-core 3.5GHz system with no other workloads)
    * Ubuntu 20.04.5
    * Kernel 5.4.0-126-generic
    * Kubelet, kubeadm, kubectl v1.24.0-00
