### ISSUE TITLE
iam: `AccessKey` CRD connection attributes missing + strange...

### ISSUE THREAD

**Issue by lorand-plensys** [upbound/provider-aws#479]
### What happened?

When creating `AccessKey` for a `IAM` `User` some credentials are missing from Connection. Only `attribute.secret` and `attribute.ses_smtp_password_v4` are present in the secret, but I would expect to have `accessKey` (or username) and `secretAccessKey` (or password). The  `attribute.secret` is actually the `secretAccessKey`. The `accessKey` is missing with no replacement.

As Connection Details are not part of the contract (documentation) there is no way to tell if this is an actual bug. As there is no other way to extract real credentials (access key and secret) but with Composition, I think this is a bug. 

### How can we reproduce it?

Replace selector to match an existing IAM User and execute:

```yaml
apiVersion: iam.aws.upbound.io/v1beta1
kind: AccessKey
metadata:
  namespace: test
  name: test-access-key
spec:
  deletionPolicy: Delete
  forProvider:
    userSelector:
      matchLabels:
        "crossplane.io/composite": simplebucket-example-jsk4w
  writeConnectionSecretToRef:
    namespace: test
    name: test-access-key
```

Check the created secret:  

```bash
kubectl get secrets/test-access-key -n test -o yaml
```

`data` contains only the two fields:
```yaml
data:
  attribute.secret: **********=
  attribute.ses_smtp_password_v4: **********=
```

### What environment did it happen in?

* Universal Crossplane Version: universal-crossplane-1.10.2-up.1
* Provider Version: xpkg.upbound.io/upbound/provider-aws:v0.27.0

* Kubernetes version: v1.24.8-eks-ffeb93d
* Kubernetes distribution: EKS

**Comment by mrchypark** [comment]
This may not be the best, but I made XRD and use it.

```
# xrd.yaml

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xaccessinfos.iam.example.com
spec:
  group: iam.example.com
  names:
    kind: XAccessinfo
    plural: xaccessinfos
  claimNames:
    kind: Accessinfo
    plural: accessinfos
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              namespace:
                type: string
                description: A namespace for placing resources.
              name:
                type: string
                description: |
                  Default values to use as names for each resource created.
                  An accessKey, secret, and configmap will be created, which will be {name}-access-key, {name}-access-key-secret, and {name}-access-key-id respectively.
              userRef:
                type: string
                description: The User to generate the accesskey for.
        required:
          - namepace
          - name
          - userRef
```


```
# composition.yaml

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xaccessinfos.example.com
spec:
  compositeTypeRef:
    apiVersion: iam.example.com/v1alpha1
    kind: XAccessinfo
  resources:
  - base: 
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: AccessKey
      metadata:
        name: #patched
      spec:
        forProvider:
          userRef:
            name: #patched
        writeConnectionSecretToRef:
          name: #patched
          namespace: #patched
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.userRef
      toFieldPath: spec.forProvider.userRef.name

    - type: FromCompositeFieldPath
      fromFieldPath: spec.name
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-access-key"

    - type: FromCompositeFieldPath
      fromFieldPath: spec.name
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
        - type: string
          string:
            fmt: "%s-access-key-secret"

    - type: FromCompositeFieldPath
      fromFieldPath: spec.namespace
      toFieldPath: spec.writeConnectionSecretToRef.namespace

    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.id
      toFieldPath: metadata.annotations[access-key-id]

  - base: 
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      metadata:
        name: #patched
      spec:
        forProvider:
          manifest:              
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: #patched
              namespace: #patched
            data:
              access-key-id: #patched
        providerConfigRef:
          name: default

    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.name
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-access-key-id-configmap"
    - type: FromCompositeFieldPath
      fromFieldPath: spec.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-access-key-id"
    - type: FromCompositeFieldPath
      fromFieldPath: spec.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.annotations[access-key-id]
      toFieldPath: spec.forProvider.manifest.data.access-key-id
      policy:
        fromFieldPath: Required
```

If you create these two files with kubectl apply, you can create a resource called Accessinfo. Here is an example manifests.

```
# example-use.yaml

apiVersion: iam.example.com/v1alpha1
kind: Accessinfo
metadata:
  name: ai-for-user
spec:
  namespace: default
  secret: iam-user
  user: iam-user
```

To use the above resources, you need to install the `k8s-provider`.
Accessinfo generate accesskey but not User. So, you also need to create User resource. 

You can get access-key-id from configmap `ai-for-user-access-key-id`, key `access-key-id`.
