### ISSUE TITLE
Cannot upgrade provider from v0.27 to v0.29

### ISSUE THREAD

**Issue by olympe-operator** [upbound/provider-aws#496]
### What happened?
When changing the package version fron v0.27 to v0.29, I have the following issue:

```
  Warning  SyncPackage        5m8s (x2 over 7m14s)  packages/providerrevision.pkg.crossplane.io  cannot establish control of object: domains.cloudsearch.aws.upbound.io is already controlled by ProviderRevision provider-aws-b52ad4c74cbf (UID 85da3c9a-851a-49fc-9804-09a73f8272d9)
  Warning  SyncPackage        2m9s                  packages/providerrevision.pkg.crossplane.io  cannot establish control of object: domainmailfroms.ses.aws.upbound.io is already controlled by ProviderRevision provider-aws-b52ad4c74cbf (UID 85da3c9a-851a-49fc-9804-09a73f8272d9)
``` 

### How can we reproduce it?
- Install a provider v0.27.0 using ArgoCD:
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v0.27.0
  controllerConfigRef:
    name: irsa-controllerconfig
```
- Update the package to v0.29.0
### What environment did it happen in?

* Universal Crossplane Version: v1.11.0
* Provider Version: v0.29.0
* Kubernetes version: v1.23
* Kubernetes distribution: EKS
