### ISSUE TITLE
ses: `DomainDKIM` CRD domain key is missing 

### ISSUE THREAD

**Issue by haarchri** [upbound/provider-aws#505]
### What happened?

rollout the resources:

```
kubectl get domainidentity.ses.aws.upbound.io/domain-identity-test-test-de   -o yaml

apiVersion: ses.aws.upbound.io/v1beta1
kind: DomainIdentity
metadata:
  annotations:
    crossplane.io/composition-resource-name: DomainIdentity
    crossplane.io/external-name: test.test.de
    upjet.crossplane.io/provider-meta: "null"
  labels:
    crossplane.io/claim-name: domain-identity-test-test-de
    crossplane.io/claim-namespace: xxxx
    crossplane.io/composite: domain-identity-test-test-de-xf9rv
  name: domain-identity-test-test.de
spec:
  deletionPolicy: Delete
  forProvider:
    domain: test.test.de
    region: eu-central-1
  providerConfigRef:
    name: xxxx
```

```
kubectl get domaindkim.ses.aws.upbound.io/domain-dkim-test-test-de  -o yaml

apiVersion: ses.aws.upbound.io/v1beta1
kind: DomainDKIM
metadata:
  annotations:
    crossplane.io/composition-resource-name: DomainDKIM
    crossplane.io/external-name: test.test.de
    upjet.crossplane.io/provider-meta: "null"
  labels:
    crossplane.io/claim-name: domain-dkim-test-test-de
    crossplane.io/claim-namespace: xxxx
    crossplane.io/composite: domain-dkim-test-test-de-mhp2x
  name: domain-dkim-test-test-de
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-central-1
  providerConfigRef:
    name: xxxxx
```

any reason why **domain** is missing for `DomainDKIM` resource ? - because this resource only makes sense if you deploy over `DomainIdentity` 

### How can we reproduce it?

apply the resources
### What environment did it happen in?

* Universal Crossplane Version: ** community crossplane 1.10
* Provider Version: 0.29

**Comment by ulucinar** [comment]
The `domain` argument is the naming argument for the resource and per the Crossplane resource model, the [crossplane.io/external-name](https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#external-resource-name) annotation is the authoritative source for naming the external resources. Thus, looks like we have removed the naming field from the generated CRD and using the external-name annotation in place of it. Could you please use the external-name annotation instead?

**Comment by haarchri** [comment]
and why domain ist in spec.forProvider for DomainIdentity ?

**Comment by ulucinar** [comment]
Good question indeed :)
Looks like it was lost in translation: 
- Originally, we had `aws_ses_domain_identity` configured in the same way: https://github.com/upbound/provider-aws/pull/382/files
- But then during the testing phase, its configuration was changed to `config.IdentifierFromProvider`: https://github.com/upbound/provider-aws/pull/399/files#diff-63ecf2f71a2e3ca7fdc30b99c4e9eb942448f9b3f04ec3259d45f86a2ec3df87

@steperchuk, do you remember why we had to switch the configuration to `config.IdentifierFromProvider` during the tests? What was the issue?

**Comment by svscheg** [comment]
Hi @ulucinar , @haarchri 
Seems for now we can use annotation `"aws_ses_domain_identity": config.ParameterAsIdentifier("domain"),` and we will have next output:
```
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-1
  providerConfigRef:
    name: default
```
