### ISSUE TITLE
ses: `DomainDKIM` CRD sensitive informations in .status.atProvider visible

### ISSUE THREAD

**Issue by haarchri** [upbound/provider-aws#507]
### What happened?

in `DomainDKIM` sensitive informations in .status.atProvider.dkimTokens[] 

```
kubectl get domaindkim.ses.aws.upbound.io/domain-dkim-test-test-de  -o yaml

apiVersion: ses.aws.upbound.io/v1beta1
kind: DomainDKIM
metadata:
  annotations:
    crossplane.io/composition-resource-name: DomainDKIM
    crossplane.io/external-name: test.test.de
    upjet.crossplane.io/provider-meta: "null"
  labels:
    crossplane.io/claim-name: domain-dkim-test-test-de
    crossplane.io/claim-namespace: xxxx
    crossplane.io/composite: domain-dkim-test-test-de-mhp2x
  name: domain-dkim-test-test-de
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-central-1
  providerConfigRef:
    name: xxxxx
status:
  atProvider:
    dkimTokens:
    - jdsdjknkjnscjknsdcjkcndskjcndskjcnj
    - idjifsdjokcnsdkcnsdklcnlsncklsdncksdn
    - kdklajdklasjdkasjdasjdlkasdjlkasdj
    id: test.test.de
```

### What environment did it happen in?

* Universal Crossplane Version: ** crossplane community 1.10
* Provider Version: v0.29.0
