### ISSUE TITLE
ses: `DomainIdentity` CRD sensitive informations in .status.atProvider visible

### ISSUE THREAD

**Issue by haarchri** [upbound/provider-aws#508]
### What happened?

in DomainIdentity sensitive informations in .status.atProvider.verificationToken

```
kubectl get domainidentity.ses.aws.upbound.io/domain-identity-test-test-de   -o yaml

apiVersion: ses.aws.upbound.io/v1beta1
kind: DomainIdentity
metadata:
  annotations:
    crossplane.io/composition-resource-name: DomainIdentity
    crossplane.io/external-name: test.test.de
    upjet.crossplane.io/provider-meta: "null"
  labels:
    crossplane.io/claim-name: domain-identity-test-test-de
    crossplane.io/claim-namespace: xxxx
    crossplane.io/composite: domain-identity-test-test-de-xf9rv
  name: domain-identity-test-test.de
spec:
  deletionPolicy: Delete
  forProvider:
    domain: test.test.de
    region: eu-central-1
  providerConfigRef:
    name: xxxx
status:
  atProvider:
    arn: arn:aws:ses:eu-central-1:12345678910:identity/test.test.de
    id: test.test.de
    verificationToken: sdkfnsdlkfalskkalsdklasdjlkasdjkls==
```

### What environment did it happen in?

* Universal Crossplane Version: crossplane community 1.10
* Provider Version: v0.29.0
