### ISSUE TITLE
Cognito: `UserPool` CRD has incorrect restriction on lambdaConfig size

### ISSUE THREAD

**Issue by thekaleidoscope** [upbound/provider-aws#615]
### What happened?

Cognito UserPool doesn't allow lambdaConfig to be created with more than one item, it errors out with 
```
Warning  CannotObserveExternalResource  3m31s (x4227 over 3d2h)  managed/cognitoidp.aws.upbound.io/v1beta1, kind=userpool  cannot run refresh: refresh failed: Too many lambda_config blocks: No more than 1 "lambda_config" blocks are allowed
```
Official Docs of Upbound say no such restriction [UpboundUserPoolDocs](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.31.0/resources/cognitoidp.aws.upbound.io/UserPool/v1beta1)

Cognito UserPool has lambdaConfig which got translated from [Terraform definition](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/cognitoidp/user_pool.go#L231), and has an incorrect retriction of `MaxItems: 1`on the lambdaConfig items.

The official API documentation of AWS Cognito User Pool doesn't have such restriction and also has structure of Map.

User Pool Syntax: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPool.html#API_CreateUserPool_RequestSyntax
Lambda Config Syntax: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_LambdaConfigType.html

The Terraform provider somehow works around this to allow multiple lambda config elements as visible in their [example](https://github.com/hashicorp/terraform-provider-aws/blob/main/examples/cognito-user-pool/main.tf#L109)

### How can we reproduce it?

Create Cognito UserPool with more than one lambdaConfig Item 

### What environment did it happen in?

* Universal Crossplane Version: v1.10.1
* Provider Version: v0.30.0

I also opened a bug card in [terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws/) [#30139](https://github.com/hashicorp/terraform-provider-aws/issues/30139)

**Comment by thekaleidoscope** [comment]
I discovered that I could get multiple lambda triggers to work if i defined the map inside first element of the array, like:

```
apiVersion: cognitoidp.aws.upbound.io/v1beta1
kind: UserPool
spec:
  forProvider:
    name: cognito-name
    ...
    lambdaConfig:
      -
        postAuthentication: arn:aws:lambda:us-west-1:123456789012:function:my-function
        postConfirmation: arn:aws:lambda:us-west-1:123456789012:function:my-function
        preAuthentication: arn:aws:lambda:us-west-1:123456789012:function:my-function
        preSignUp: arn:aws:lambda:us-west-1:123456789012:function:my-function
        preTokenGeneration: arn:aws:lambda:eu-west-1:123456789012:function:my-function
 ...
```

at least the documentation and the example should be updated
