### ISSUE TITLE
memorydb: Cluster writeConnectionSecret missing fields 

### ISSUE THREAD

**Issue by ajrajkumar** [upbound/provider-aws#626]
The MemoryDb Cluster resource does not write any information to the connection secret and does not create secret using publishConnectionDetails.

What happened?
Connection secret is getting created properly, but without any connection data

How can we reproduce it?
Create an MemoryDB cluster resource  and check the connection secret.
Here the sample I have used.

``` yaml
apiVersion: memorydb.aws.upbound.io/v1beta1
kind: Cluster
metadata:
    annotations:
      upjet.upbound.io/manual-intervention: This resource has a password secret reference.
    name: memorydb-cross-instance
    namespace: default
spec:
    providerConfigRef:
      name: default
    forProvider:
       aclName: open-access
       subnetGroupName: crossplane-memorydb-bm5gr-8tzbt
       region: us-east-2
       nodeType: db.t4g.small
    writeConnectionSecretToRef:
      namespace: default
      name: memorydbout-ws
    publishConnectionDetailsTo:
      name: memorydbout-pub
```
```
kubectl get secret memorydbout-ws
NAME                        TYPE                                               DATA   AGE
memorydbout-ws   connection.crossplane.io/v1alpha1   0      19h
```
What environment did it happen in?
Universal Crossplane Version: 1.11.2-up.2
Provider Version: v0.31
Cloud provider or hardware configuration: AWS db.t4g.small nodes
Kubernetes version (use kubectl version): v1.26.3
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): EKS
OS (e.g. from /etc/os-release): Amazon Linux 2
Kernel (e.g. uname -a): N/A
