### ISSUE TITLE
`aws_networkfirewall_firewall_policy` missing ref/selector for RuleGroup

### ISSUE THREAD

**Issue by haarchri** [upbound/provider-aws#658]
### What happened?

`aws_networkfirewall_firewall_policy ` resources is missing ref/selector for RuleGroup  in `firewall_policy.stateless_rule_group_reference.resource_arn` and `firewall_policy.stateful_rule_group_reference.resource_arn`

```
error: error validating "default-policy.yaml": error validating data: [ValidationError(FirewallPolicy.spec.forProvider.firewallPolicy[0].statefulRuleGroupReference[0]): unknown field "resourceArnRef" in io.upbound.aws.networkfirewall.v1beta1.FirewallPolicy.spec.forProvider.firewallPolicy.statefulRuleGroupReference, ValidationError(FirewallPolicy.spec.forProvider.firewallPolicy[0].statefulRuleGroupReference[1]): unknown field "resourceArnRef" in io.upbound.aws.networkfirewall.v1beta1.FirewallPolicy.spec.forProvider.firewallPolicy.statefulRuleGroupReference]; if you choose to ignore these errors, turn validation off with --validate=false
```

### How can we reproduce it?
create the following manifest:

```yaml
apiVersion: networkfirewall.aws.upbound.io/v1beta1
kind: FirewallPolicy
metadata:
  name: default-policy
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-central-1
    name: default-policy
    firewallPolicy:
      - statelessDefaultActions:
          - "aws:forward_to_sfe"
        statelessFragmentDefaultActions:
          - "aws:pass"
        statelessRuleGroupReference:
          - resourceArnRef:
              name: forward-all
            priority: 2
        statefulRuleGroupReference:
          - resourceArnRef:
              name: allow-domainlist
          - resourceArnRef:
              name: deny
```

### What environment did it happen in?

* Crossplane Version: 1.11.3
* Provider Version: 0.31.0
* Kubernetes Version:  
* Kubernetes Distribution:  EKS 1.23
