### ISSUE TITLE
How to pass env vars to the provider ? Proxy requirement

### ISSUE THREAD

**Issue by eperdeme** [upbound/provider-aws#710]
### What happened?
I've told the provider to use IRSA and it is attempting to call out to STS. My security requires all connections to be sent via a web proxy. I can't find any way to pass in proxy or environment variables to the provider, I would have expected it to be via ProviderConfig but I can not see any reference to passing custom env params.

I can pass proxy information to the crossplane main app via the helm chart;

```
  extraEnvVarsCrossplane:
    http_proxy: http://webproxy:3128
    https_proxy: http://webproxy:3128
    no_proxy: "{{ cookiecutter.aws_region }}.eks.amazonaws.com, .internal, .local, .plc, 10.0.0.0/8, 100.0.0.0/8, 127.0.0.1, 169.254.169.254, 169.254.170.2, api.ecr.eu-west-1.amazonaws.com, dkr.ecr.eu-west-1.amazonaws.com, dynamodb.{{ cookiecutter.aws_region }}.amazonaws.com, elasticfilesystem.{{ cookiecutter.aws_region }}.amazonaws.com, instance-data, localhost, logs.{{ cookiecutter.aws_region }}.amazonaws.com, monitoring.{{ cookiecutter.aws_region }}.amazonaws.com, s3.{{ cookiecutter.aws_region }}.amazonaws.com, .s3.{{ cookiecutter.aws_region }}.amazonaws.com"
```

### How can we reproduce it?
Attempt to pass in key:value env vars to the provider and verify it with a kubectl describe.

### What environment did it happen in?

* Crossplane Version: 1.12.1
* Provider Version: 0.35.0
* Kubernetes Version:
``` 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"darwin/amd64"}
```
```
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.13-eks-0a21954", GitCommit:"6305d65c340554ad8b4d7a5f21391c9fa34932cb", GitTreeState:"clean", BuildDate:"2023-04-15T00:33:45Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes Distribution: EKS

**Comment by eperdeme** [comment]
Actually went back and re-thought about how each provider works and figured it out.

```
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: irsa-controllerconfig
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::x:role/eu-west-1-eks-shared-crossplane
spec:
  env:
    - name: http_proxy
      value:  http://webproxy:3128
    - name: https_proxy
      value:  http://webproxy:3128
    - name: no_proxy
      value: eu-west-1.eks.amazonaws.com, .internal, .local, .plc, 10.0.0.0/8, 100.0.0.0/8, 127.0.0.1, 169.254.169.254, 169.254.170.2, api.ecr.eu-west-1.amazonaws.com, dkr.ecr.eu-west-1.amazonaws.com, dynamodb.eu-west-1.amazonaws.com, elasticfilesystem.eu-west-1.amazonaws.com, instance-data, localhost, logs.eu-west-1.amazonaws.com, monitoring.eu-west-1.amazonaws.com, s3.eu-west-1.amazonaws.com, .s3.eu-west-1.amazonaws.com
```
