### ISSUE TITLE
KMS Alias READY status becomes FALSE after upbound/provider-aws pod is restarted

### ISSUE THREAD

**Issue by project-administrator** [upbound/provider-aws#722]
### What happened?
We create the KMS Alias with a composition. 
After all of the resources created by the composition are `READY: True` and `SYNCED: True`, we restart the `upbound/provider-aws` controller pod (e.g. because the k8s nodes are being rolled). After few minutes, the Alias.kms.aws.upbound.io managed resource status becomes `READY: false`, `SYNCED: True`. 
`kubectl describe` for the Alias.kms.aws.upbound.io managed resource shows the following:
```
    Message:               apply failed: creating KMS Alias (alias/az3-lwcqf-6fl6x): AlreadyExistsException: An alias with the name arn:aws:kms:eu-west-2:123456789012:alias/az3-lwcqf-6fl6x already exists: 
    Reason:                ApplyFailure
    Status:                False
    Type:                  LastAsyncOperation
```

### How can we reproduce it?
- create the below resource: XRD, Composition, Claim
- wait few minutes to verify that all managed resources are `READY: True`, `SYNCED: True`
- restart the `upbound/provider-aws` controller pod
- check the managed resources status becomes `READY: False`, `SYNCED: True` for the Alias.kms.aws.upbound.io --- this is a bug and this should not happen. Provider restart should not trigger such behavior. 

XRD definition:
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdataencryption.infra.cloud.company.com
  labels:
    resource: kms-replicated
  annotations:
    owner: platform-builders
spec:
  group: infra.cloud.company.com
  names:
    kind: XDataEncryption
    plural: xdataencryption
  claimNames:
    kind: DataEncryption
    plural: dataencryption
  defaultCompositionRef:
    name: kms
  versions:
  - name: v1gamma1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  provider:
                    type: string
                    description: Name of the aws provider to reference in the composition patchSets
                    default: aws-provider-upbound
                    example:
                      - aws: 'aws-provider-upbound'
                      - (Sets the AWS provider to the upbound maintained one.)
                      - (CAn be one of 'aws-provider' or 'aws-provider-upbound')
                    enum:
                      - aws-provider-upbound
                      - aws-provider
                  region:
                    type: string
                    description: Set an AWS region where this bucket should be created.
                    example:
                      - region: eu-west-1
                      - (Set to one of eu-west-1 (Ireland), eu-west-2 (London), or us-east-2 (Ohio))
                    enum:
                      - eu-west-1
                      - eu-west-2
                      - us-east-2
                  customer_uuid:
                    type: string
                    description: Set the customer UUID
                    example:
                      - customer_uuid: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
                      - (Sets the unique customer identifier in UUID format.)
                  customer:
                    type: string
                    description: Set the customer name
                    example:
                      - customer: az
                      - (Sets the unique short customer identifier.)
                      - (e.g. astraeneca == az)
                  delete_key_in_days:
                    type: number
                    description: "Set, in days, when this key should be removed completely when deleted (min 7 - max 30)."
                    oneOf:
                      - pattern: '([7-9]|[12][0-9]|30)'
                    example:
                      - delete_key_in_days: 9
                      - (Setting this to 9 will delete the key from AWS 9 days after the Delete call has been issued.)
                    default: 7
                  cmk_spec:
                    type: string
                    description: "Set this CMK key specification."
                    example:
                      - cmk_spec: SYMMETRIC_DEFAULT
                      - (Set to one of SYMMETRIC_DEFAULT, RSA_2048, RSA_3072, RSA_4096, HMAC_256, ECC_NIST_P256, ECC_NIST_P384, ECC_NIST_P521, or ECC_SECG_P256K1.)
                    enum:
                      - SYMMETRIC_DEFAULT
                      - RSA_2048
                      - RSA_3072
                      - RSA_4096
                      - HMAC_256
                      - ECC_NIST_P256
                      - ECC_NIST_P384
                      - ECC_NIST_P521
                      - ECC_SECG_P256K1
                    default: SYMMETRIC_DEFAULT
                  cmk_key_usage:
                    type: string
                    description: 'Set this CMK intended usage'
                    example:
                      - cmk_key_usage: ENCRYPT_DECRYPT
                      - (Set to one of ENCRYPT_DECRYPT, SIGN_VERIFY, or GENERATE_VERIFY_MAC)
                    enum:
                      - ENCRYPT_DECRYPT
                      - SIGN_VERIFY
                      - GENERATE_VERIFY_MAC
                    default: ENCRYPT_DECRYPT
                  environment:
                    type: string
                    description: Set this tenant environment.
                    example:
                      - environment: dev
                      - (Set to one of dev, impl, sbox, or prod)
                    enum:
                      - dev
                      - impl
                      - sbox
                      - prod
                  role_arn:
                    type: string
                    description: Set the IAM role ARN to be included in the policies
                    example:
                      - roleARN: <role_arn>
                      - (Set IAM role ARN)
                  tags:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                required:
                - region
                - cmk_spec
                - cmk_key_usage
                - delete_key_in_days
            required:
            - parameters
            oneOf:
              - required:
                  - environment
                  - delete_key_in_days
                  - cmk_spec
                  - cmk_key_usage
                  - role_arn
                  - tags
                  - customer
                  - customer_uuid
                  - provider
              - not:
                  required:
                    - environment
                    - delete_key_in_days
                    - cmk_spec
                    - cmk_key_usage
                    - role_arn
                    - tags
                    - customer
                    - customer_uuid
                    - provider
          status:
            type: object
            properties:
              cmk_arn:
                description: CMK (Customer Managed Key) ARN
                type: string
              cmk_id:
                description: CMK (Customer Managed Key) ID
                type: string
              cmk_repl_arn:
                description: Replica CMK (Customer Managed Key) ARN
                type: string
```

Composition (replace "123456789012" with your AWS account ID):
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kms
  labels:
    crossplane.io/xrd: xdataencryption.infra.cloud.company.com
spec:
  writeConnectionSecretsToNamespace: operators
  compositeTypeRef:
    apiVersion: infra.cloud.company.com/v1gamma1
    kind: XDataEncryption
  patchSets:
  - name: provider_aws_upbound
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.provider
      toFieldPath: spec.providerConfigRef.name
  - name: region
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
  - name: tagging
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.tags
      toFieldPath: spec.forProvider.tags
  - name: labeling
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.tags
      toFieldPath: metadata.labels
  resources:
  - name: primary_cmk
    base:
      apiVersion: kms.aws.upbound.io/v1beta1
      kind: Key
      metadata:
        labels:
          resource: primary-cmk
      spec:
        forProvider:
          enableKeyRotation: true
          isEnabled: true
          multiRegion: true
    patches:
    - type: PatchSet
      patchSetName: provider_aws_upbound
    - type: PatchSet
      patchSetName: region
    - type: PatchSet
      patchSetName: tagging
    - type: PatchSet
      patchSetName: labeling
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: spec.parameters.customer
          - fromFieldPath: spec.parameters.environment
        strategy: string
        string:
          fmt: "Primary region CMK for %s-%s."
      toFieldPath: spec.forProvider.description
    - fromFieldPath: spec.parameters.cmk_spec
      toFieldPath: spec.forProvider.customerMasterKeySpec
    - fromFieldPath: spec.parameters.delete_key_in_days
      toFieldPath: spec.forProvider.deletionWindowInDays
    - fromFieldPath: spec.parameters.cmk_key_usage
      toFieldPath: spec.forProvider.keyUsage
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.cmk_arn
      policy:
        fromFieldPath: Required
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.id
      toFieldPath: status.cmk_id
      policy:
        fromFieldPath: Required
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: spec.parameters.customer
          - fromFieldPath: spec.parameters.environment
        strategy: string
        string:
          fmt: | 
           {
               "Version": "2012-10-17",
               "Statement": [
                 {
                     "Sid": "EnableRootAccessToCMK %s-%s",
                     "Effect": "Allow",
                     "Principal": {
                         "AWS": "arn:aws:iam::123456789012:root"
                     },
                     "Action": "kms:*",
                     "Resource": "*"
                 },
                 {
                     "Sid": "Enable S3 to work with encryption.",
                     "Effect": "Allow",
                     "Principal": {
                         "Service": "s3.amazonaws.com"
                     },
                     "Action": [
                         "kms:GenerateDataKey",
                         "kms:Decrypt"
                     ],
                     "Resource": "*"
                 }
               ]
           }
      toFieldPath: spec.forProvider.policy
  - name: primary_cmk_alias
    base:
      apiVersion: kms.aws.upbound.io/v1beta1
      kind: Alias
      # spec:
      #   forProvider:
      #     targetKeyIdSelector:
      #       matchLabels:
      #         resource: primary-cmk
    patches:
    - type: PatchSet
      patchSetName: provider_aws_upbound
    - type: PatchSet
      patchSetName: region
    - type: PatchSet
      patchSetName: labeling
    - fromFieldPath: status.cmk_arn
      toFieldPath: spec.forProvider.targetKeyId
      policy:
        fromFieldPath: Required
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: spec.parameters.customer
          - fromFieldPath: spec.parameters.environment
        strategy: string
        string:
          fmt: "%s-%s-key"
      toFieldPath: "metadata.annotations[crossplane.io/external-name]"
      policy:
        fromFieldPath: Required
  - name: replica_cmk
    base:
      apiVersion: kms.aws.upbound.io/v1beta1
      kind: ReplicaKey
      metadata:
        labels:
          resource: replica-cmk
      # spec:
      #   forProvider:
      #     primaryKeyArnSelector:
      #       matchLabels:
      #         resource: primary-cmk
    patches:
    - type: PatchSet
      patchSetName: provider_aws_upbound
    - type: PatchSet
      patchSetName: tagging
    - type: PatchSet
      patchSetName: labeling
    - fromFieldPath: status.cmk_arn
      toFieldPath: spec.forProvider.primaryKeyArn
      policy:
        fromFieldPath: Required
    - fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
      transforms:
          - type: map
            map: 
              eu-west-1: eu-central-1
              eu-west-2: eu-central-1
              us-east-2: us-west-1
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: spec.parameters.customer
          - fromFieldPath: spec.parameters.environment
        strategy: string
        string:
          fmt: "Replica region CMK for %s-%s."
      toFieldPath: spec.forProvider.description
    - fromFieldPath: spec.parameters.delete_key_in_days
      toFieldPath: spec.forProvider.deletionWindowInDays
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.cmk_repl_arn
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: spec.parameters.customer
          - fromFieldPath: spec.parameters.environment
        strategy: string
        string:
          fmt: | 
           {
               "Version": "2012-10-17",
               "Statement": [
                 {
                     "Sid": "EnableRootAccessToCMK %s-%s",
                     "Effect": "Allow",
                     "Principal": {
                         "AWS": "arn:aws:iam::123456789012:root"
                     },
                     "Action": "kms:*",
                     "Resource": "*"
                 },
                 {
                     "Sid": "AllowS3ToWorkWithEncryption",
                     "Effect": "Allow",
                     "Principal": {
                         "Service": "s3.amazonaws.com"
                     },
                     "Action": [
                         "kms:GenerateDataKey",
                         "kms:Decrypt"
                     ],
                     "Resource": "*"
                 }
               ]
           }
      toFieldPath: spec.forProvider.policy
  - name: replica_cmk_alias
    base:
      apiVersion: kms.aws.upbound.io/v1beta1
      kind: Alias
      # spec:
      #   forProvider:
      #     targetKeyIdSelector:
      #       matchLabels:
      #         resource: replica-cmk
    patches:
    - type: PatchSet
      patchSetName: provider_aws_upbound
    - type: PatchSet
      patchSetName: labeling
    - fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
      transforms:
          - type: map
            map: 
              eu-west-1: eu-central-1
              eu-west-2: eu-central-1
              us-east-2: us-west-1
    - fromFieldPath: status.cmk_repl_arn
      toFieldPath: spec.forProvider.targetKeyId
      policy:
        fromFieldPath: Required
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: spec.parameters.customer
          - fromFieldPath: spec.parameters.environment
        strategy: string
        string:
          fmt: "%s-%s-key"
      toFieldPath: "metadata.annotations[crossplane.io/external-name]"
      policy:
        fromFieldPath: Required
```

Claim:
```
apiVersion: infra.cloud.company.com/v1gamma1
kind: DataEncryption
metadata:
  name: cmk3
  namespace: default
spec:
  parameters:
    region: eu-west-1
    customer_uuid: 33333333-1508-46d8-8ec4-333333333333
    customer: az3
    environment: dev
    tags:
      tag1: value1
```
### What environment did it happen in?

* Crossplane Version: 1.12.1
* Provider Version: v0.35.0
* Kubernetes Version: v1.27.1
* Kubernetes Distribution: EKS
