### ISSUE TITLE
Queue: missing data.endpoint information from Kubernetes secret

### ISSUE THREAD

**Issue by covidium** [upbound/provider-aws#730]
### What happened?
The Queues (SQS) configured with do not publish the endpoint inside the k8s secret. I've used both publishConnectionDetailsTo and writeConnectionSecretToRef and in both cases the field data: was missing.

### How can we reproduce it?
Create a simple Queue, check out the secret for the data: field which it should have the endpoint entry indicating the queue address.
```yaml
apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  name: "my-dummy-queue"
  namespace: "default"
spec:
  providerConfigRef:
    name: "default"
  writeConnectionSecretToRef:
    name: "my-dummy-queue"
    namespace: "default"
  forProvider:
    name: "my-dummy-queue"
    region: "eu-west-1"
    delaySeconds: 300
    fifoQueue: false
    messageRetentionSeconds: 900
```

### What environment did it happen in?

* Crossplane Version: 1.12.1
* Provider Version: 0.35.0
* Kubernetes Version: v1.27.1-eks-2f008fe
* Kubernetes Distribution: EKS
