### ISSUE TITLE
provider-aws-cognitoidp:v0.36.0 User Pool Client Validation Error

### ISSUE THREAD

**Issue by humoflife** [upbound/provider-aws#752]
### What happened?

When creating a Cognito user pool client, the following error message occurs:
```
observe failed: cannot run refresh: refresh failed: reading Amazon Cognito IDP (Identity Provider) User Pool Client (): InvalidParameter: 1 validation error(s) found.
      - minimum field size of 1, DescribeUserPoolClientInput.ClientId.
```

The expected behavior is for the user pool client to be created without the error.

### How can we reproduce it?

You can reproduce the issue using the example at https://github.com/upbound/provider-aws/blob/main/examples/cognitoidp/userpooluicustomization.yaml.

You will see the following error.
```
    Message:               observe failed: cannot run refresh: refresh failed: reading Amazon Cognito IDP (Identity Provider) User Pool Client (): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DescribeUserPoolClientInput.ClientId.
```

### What environment did it happen in?

* Crossplane Version: 12.2
* Provider Version: provider-aws-cognitoidp:v0.36.0
* Kubernetes Version:  1.27 
* Kubernetes Distribution:  EKS

**Comment by ytsarev** [comment]
I found a temporary workaround to set external-name annotation, it will bypass the validation

```
apiVersion: cognitoidp.aws.upbound.io/v1beta1
kind: UserPoolClient
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
  annotations:
    crossplane.io/external-name: anyvalue # <<< workaround
spec:
  forProvider:
    name: example
    region: us-west-1
    userPoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
```

and will update the external-name with dynamic id after the reconciliation 

```
NAME                                               READY   SYNCED   EXTERNAL-NAME                AGE
userpoolclient.cognitoidp.aws.upbound.io/example   True    True     5jnfa12tfniormc00s1ih1e6c8   4m50s
```

It is **not** a long term solution as the id is not getting properly crafted according to the https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool_client#import and it should not fail without the external-name annotation in general
