### ISSUE TITLE
Custom endpoint in the ProviderConfig crashes the provider

### ISSUE THREAD

**Issue by ItielOlenick** [upbound/provider-aws#780]
### What happened?
When trying to use using a custom [endpoint](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.37.0/resources/aws.upbound.io/ProviderConfig/v1beta1#doc:spec-endpoint-services) for services, the provider crashes.

### How can we reproduce it?

Create the following ProviderConfig:

```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-aws-creds
      namespace: crossplane-system
      key: credentials
  endpoint:
    hostnameImmutable:  true
    services:
      - apigateway
      - apigatewayv2
      - cloudformation
      - cloudwatch
      - dynamodb
      - ec2
      - es
      - elasticache
      - firehose
      - iam
      - kinesis
      - lambda
      - rds
      - redshift
      - route53
      - s3
      - secretsmanager
      - ses
      - sns
      - sqs
      - ssm
      - stepfunctions
      - sts
    url:
      static:                   http://127.0.0.1:4566
      type:                     Static
  skip_credentials_validation:  true
  skip_metadata_api_check:      true
  skip_requesting_account_id:   true
```

Run `make run` from source

Add a resource from the examples

Results in:

```
2023-07-08T00:11:11+03:00       INFO    Starting workers        {"controller": "managed/sagemaker.aws.upbound.io/v1beta1, kind=modelpackagegroup", "controllerGroup": "sagemaker.aws.upbound.io", "controllerKind": "ModelPackageGroup", "worker count": 10}
2023-07-08T00:11:11+03:00       INFO    Observed a panic in reconciler: assignment to entry in nil map  {"controller": "managed/sns.aws.upbound.io/v1beta1, kind=topic", "controllerGroup": "sns.aws.upbound.io", "controllerKind": "Topic", "Topic": {"name":"example"}, "namespace": "", "name": "example", "reconcileID": "279c90f9-05e6-4780-b093-00fdf3f4bdca"}
2023-07-08T00:11:11+03:00       INFO    Starting workers        {"controller": "managed/cloudfront.aws.upbound.io/v1beta1, kind=originrequestpolicy", "controllerGroup": "cloudfront.aws.upbound.io", "controllerKind": "OriginRequestPolicy", "worker count": 10}
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

goroutine 20765 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x3ab9be0, 0x4d62eb0})
        runtime/panic.go:884 +0x213
github.com/upbound/provider-aws/internal/clients.DefaultTerraformSetupBuilder({0x4d95bf0, 0xc008a7c840}, {0x4da77e0?, 0xc00076e120?}, {0x4e46690?, 0xc002481400?}, 0xc007db1380, 0xc00b19e580)
        github.com/upbound/provider-aws/internal/clients/aws.go:187 +0x6c9
github.com/upbound/provider-aws/internal/clients.SelectTerraformSetup.func1({0x4d95bf0, 0xc008a7c840}, {0x4da77e0, 0xc00076e120}, {0x4e46690?, 0xc002481400?})
        github.com/upbound/provider-aws/internal/clients/aws.go:81 +0x325
github.com/upbound/upjet/pkg/controller.(*Connector).Connect(0xc000a08d20, {0x4d95bf0, 0xc008a7c840}, {0x4e46690, 0xc002481400})
        github.com/upbound/upjet@v0.9.0-rc.0.0.20230502154751-645d7260d814/pkg/controller/external.go:93 +0xd6
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*NopDisconnecter).Connect(0xc002654120?, {0x4d95bf0?, 0xc008a7c840?}, {0x4e46690?, 0xc002481400?})
        github.com/crossplane/crossplane-runtime@v0.20.0-rc.0.0.20230406155702-4e1673b7141f/pkg/reconciler/managed/reconciler.go:216 +0x35
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc000efd980, {0x4d95c28, 0xc008a7c780}, {{{0x0, 0x0}, {0xc002194e36, 0x7}}})
        github.com/crossplane/crossplane-runtime@v0.20.0-rc.0.0.20230406155702-4e1673b7141f/pkg/reconciler/managed/reconciler.go:786 +0x2383
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0xc000a08e60, {0x4d95c28, 0xc008a7c780}, {{{0x0?, 0x0?}, {0xc002194e36?, 0x40de67?}}})
        github.com/crossplane/crossplane-runtime@v0.20.0-rc.0.0.20230406155702-4e1673b7141f/pkg/ratelimiter/reconciler.go:54 +0x16b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x4d95c28?, {0x4d95c28?, 0xc008a7c780?}, {{{0x0?, 0x39a5560?}, {0xc002194e36?, 0x0?}}})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000f68820, {0x4d95b80, 0xc0002cedc0}, {0x3c68ac0?, 0xc0015d0840?})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x35f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000f68820, {0x4d95b80, 0xc0002cedc0})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x587
make: *** [Makefile:129: run] Error 2
```

### What environment did it happen in?

Both local provider running from source and provider from xpkg.upbound.io/upbound/provider-aws:/v0.37.0
