### ISSUE TITLE
Error when creating group.cloudwatchlogs object

### ISSUE THREAD

**Issue by akesser** [upbound/provider-aws#795]
### What happened?

When I create an group.cloudwatchlogs.aws.upbound.io object with a value in spec.forProvider.retentionInDays, the log group gets created with retention "never expire" and the managed resource shows the following error: 

```
observe failed: cannot run plan: plan failed: Instance cannot be destroyed:
      Resource aws_cloudwatch_log_group.example-loggroup-abcd-abcd has
      lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed.
      To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy
      or reduce the scope of the plan using the -target flag.
```

when you look at the terraform plan command inside the provider pod you see something like this:
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
Terraform will perform the following actions:
# aws_cloudwatch_log_group.example-loggroup-abcd-abcd is tainted, so must be replaced
-/+ resource "aws_cloudwatch_log_group" "example-loggroup-abcd-abcd6" {
   ~ arn        = "...ARN..." -> (known after apply)
   ~ id        = "example-loggroup" -> (known after apply)
    name       = "example-loggroup"
   + name_prefix    = (known after apply)
   ~ retention_in_days = 0 -> 5
    tags       = {
      ...
    }
    # (2 unchanged attributes hidden)
  }
Plan: 1 to add, 0 to change, 1 to destroy.
```

### How can we reproduce it?

create an group.cloudwatchlogs.aws.upbound.io object with a value in spec.forProvider.retentionInDays
### What environment did it happen in?

* Crossplane Version: v1.12.1-up.2
* Provider Version: v0.37.0-rc.0.19.g6dc15fb4
* Kubernetes Version: v1.24
* Kubernetes Distribution: EKS

**Comment by haarchri** [comment]
can you provide full manifest ?

**Comment by akesser** [comment]
We see the same behavior for groups without an retentionInDays set, I updated the title of the issue

**Comment by akesser** [comment]
```
apiVersion: cloudwatchlogs.aws.upbound.io/v1beta1
kind: Group
metadata:
  name: example-loggroup
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-central-1
    retentionInDays: 5    
    tags:
      example-tag: example
  managementPolicy: FullControl
  providerConfigRef:
    name: example-config
```
