### ISSUE TITLE
ECS Service will always execute replace on each polling interval

### ISSUE THREAD

**Issue by mhoshi-vm** [upbound/provider-aws#825]
### What happened?

I am seeing ECS service being recreated on every polling interval.
Debugging, I see that the at the terraform plan phase it is always trying to remove the revision from the `taskDefinition`

```
  # aws_ecs_service.test2-ecs-ns1 will be updated in-place
  ~ resource "aws_ecs_service" "test2-ecs-ns1" {
        id                                 = "arn:aws:ecs:us-west-2:XXXXXXX:service/hoge/test2-ecs-ns1"
        name                               = "test2-ecs-ns1"
        tags                               = {
            "crossplane-kind"           = "service.ecs.aws.upbound.io"
            "crossplane-name"           = "test2-ecs-ns1"
            "crossplane-providerconfig" = "aws-provider"
        }
      ~ task_definition                    = "test2-ecs-ns1:16" -> "test2-ecs-ns1"
        # (16 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }
```

Here is my full manifest

```
apiVersion: ecs.aws.upbound.io/v1beta1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: ecs-test
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: ecs
    app.kubernetes.io/component: run
    carto.run/workload-name: test2
  name: test2-ecs-ns1
  annotations:
    boot.spring.io/version: 3.1.2
    conventions.carto.run/applied-conventions: |-
      appliveview-sample/app-live-view-appflavour-check
      spring-boot-convention/auto-configure-actuators-check
      spring-boot-convention/spring-boot
      spring-boot-convention/spring-boot-graceful-shutdown
      spring-boot-convention/spring-boot-web
      spring-boot-convention/spring-boot-actuator
      spring-boot-convention/spring-boot-actuator-probes
      spring-boot-convention/app-live-view-appflavour-check
      spring-boot-convention/app-live-view-connector-boot
      spring-boot-convention/app-live-view-appflavours-boot
    developer.conventions/target-containers: workload
spec:
  providerConfigRef:
    name: aws-provider
  deletionPolicy: Delete
  forProvider:
    deploymentCircuitBreaker:
    - enable: false
      rollback: false
    deploymentController:
    - type: ECS
    deploymentMaximumPercent: 200
    deploymentMinimumHealthyPercent: 100
    desiredCount: 1
    cluster: hoge
    launchType: FARGATE
    forceNewDeployment: true
    platformVersion: LATEST
    propagateTags: NONE
    schedulingStrategy: REPLICA
    region: us-west-2
    taskDefinitionRef:
      name: test2-ecs-ns1
    networkConfiguration:
    - subnets:
      - subnet-074a9adfdda8e8e47
  initProvider: {}
  managementPolicies:
  - '*'
```

### How can we reproduce it?

Use a similar above manifest and wait until the polling interval

### What environment did it happen in?

* Crossplane Version: 1.12.up-2
* Provider Version: 0.38.0
* Kubernetes Version: 1.26 
* Kubernetes Distribution: EKS
