### ISSUE TITLE
BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region at endpoint '', bucket is in 'us-east-2'

### ISSUE THREAD

**Issue by codemug** [upbound/provider-aws#841]
### What happened?
I'm trying to create a test S3 bucket in the `eu-west-1` region and it's failing with this error:

```
"observe failed: cannot run refresh: refresh failed: reading Amazon S3
(Simple Storage) Bucket (crossplane-bucket-test): BucketRegionError: incorrect
region, the bucket is not in 'eu-west-1' region at endpoint '', bucket is in
'us-east-2' region\n\tstatus code: 301"
```

### How can we reproduce it?
The bucket I'm trying to create:

```yaml
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-bucket-test
spec:
  forProvider:
    region: eu-west-1
  providerConfigRef:
    name: s3-provider
```

### What environment did it happen in?

* Crossplane Version: v1.12.2
* Provider Version: v0.38.0
* Kubernetes Version: 1.23.17
* Kubernetes Distribution: EKS in eu-west-1 region

Additional configuration information:

I'm using IRSA to authenticate with AWS. That's configured correctly since I'm also using IAM provider and that works perfectly. Here's my ProviderConfig for S3:

```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: s3-provider
spec:
  credentials:
    source: IRSA
```

I have a separate ServiceAccount per provider each of which has a separate IAM role annotation for that particular service. 

#### Things I Tried

I tried setting up the endpoint.url.static to `https://s3.eu-west-1.amazonaws.com` in the ProviderConfig, but that didn't help. 

I've also checked my AWS console and the bucket doesn't exist already.
