### ISSUE TITLE
authParameters limitation for EventBridge Connection 

### ISSUE THREAD

**Issue by headyj** [upbound/provider-aws#871]
I'm wondering why `authParameters` is limited to a single one in EventBridge (CloudWatch) Connection. There are many examples when we require multiple parameters, and this is totally feasible with related Terraform resource:

```
resource "aws_cloudwatch_event_connection" "connection" {
  name               = "connection"
  description        = "my-connection"
  authorization_type = "API_KEY"

  auth_parameters {
    api_key {
      key   = "Authorization"
      value = "Bearer *******"
    }
    invocation_http_parameters {
      header {
        key             = "Content-Type"
        value           = "application/json"
        is_value_secret = false
      }
    }
  }

}
```

Moreover, it seems impossible to use `invocationHttpParameters` at all, as only a single `authParameters` is accepted, but one of oauth, basic or api_key must be specified:
```
cannot run refresh: refresh failed: Invalid combination of arguments: "auth_parameters.0.api_key": one of `auth_parameters.0.api_key,auth_parameters.0.basic,auth_parameters.0.oauth` must be specified
```

Finally, it seems impossible as well to put multiple parameters in the same `apiKey` (or `header` in the case of `invocationHttpParameters`:

```
cannot run refresh: refresh failed: Too many api_key blocks: No more than 1 "api_key" blocks are allowed
```
```
cannot run refresh: refresh failed: Too many invocation_http_parameters blocks: No more than 1 "invocation_http_parameters" blocks are allowed
```

So as far as I understand, there is currently no way to setup multiple parameters for a single connection

you can easily reproduce the first issue by trying to add multiple `authParameters`:

```
[...]
        spec:
          forProvider:
           
            authParameters:
              - apiKey:
                - key: "Content-Type"
                  valueSecretRef:
                    key: firstKey
                    name: firstName
                    namespace: default
              - invocationHttpParameters:
                - header: 
                  - key: Authorization
                    valueSecretRef:
                      key: firstKey
                      name: firstName
                      namespace: default
                 
```
For the 2nd, just try with a single `invocationHttpParameters`:
```
[...]
        spec:
          forProvider:
            authParameters:
              - invocationHttpParameters:
                - header:
                  - key: Authorization
                    valueSecretRef:
                      key: firstKey
                      name: firstName
                      namespace: default
```
For the 3rd, just add multiple `apiKey`  or multiple `invocationHttpParameters`:

```
[...]
        spec:
          forProvider:
            authParameters:
              - invocationHttpParameters:
                - header: 
                  - key: Authorization
                    valueSecretRef:
                      key: firstKey
                      name: firstName
                      namespace: default
                  - key: "Content-Type"
                    valueSecretRef:
                      key: secondKey
                      name: secondName
                      namespace: default
``` 
* Crossplane Version: v1.13.2
* Provider Version: provider-aws-cloudwatchevents v0.40.0
* Kubernetes Version: v1.26
* Kubernetes Distribution: EKS

**Comment by turkenf** [comment]
@headyj, please try without using the dash "-" after the first parameter.
```
[...]
        spec:
          forProvider: 
            authParameters:
              - apiKey:
                - key: "Content-Type"
                  valueSecretRef:
                    key: firstKey
                    name: firstName
                    namespace: default
                invocationHttpParameters:
                - header: 
                  - key: Authorization
                    valueSecretRef:
                      key: firstKey
                      name: firstName
                      namespace: default
```
This way I verified that the resource was created without any issues.
```
status:
  atProvider:
    arn: arn:aws:events:us-west-1:<redacted>:connection/test/<redacted>
    authParameters:
    - apiKey:
      - key: x-signature
      invocationHttpParameters:
      - header:
        - isValueSecret: false
          key: Authorization
    authorizationType: API_KEY
    description: A connection description
    id: test
    secretArn: arn:aws:secretsmanager:us-west-1:<redacted>:secret:events!connection/test/<redacted>
  conditions:
  - lastTransitionTime: "2023-10-09T11:54:57Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-10-09T11:55:36Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-10-09T11:55:10Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
  - lastTransitionTime: "2023-10-09T11:55:10Z"
    reason: Finished
    status: "True"
    type: AsyncOperation
```
I am closing this now, feel free to reopen it if you encounter any issues.
