### ISSUE TITLE
s3 doesn't populate connection details in secret

### ISSUE THREAD

**Issue by candonov** [upbound/provider-aws#886]
### What happened?

When creating s3 bucket with "writeConnectionSecretToRef" the secrets gets created but it is empty. Expected result: to have `id` (bucket name).

### How can we reproduce it?

```
cat <<EOF | kubectl create -f -
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: upbound-test-bucket-
spec:
  writeConnectionSecretToRef:
    name: test-bucket
    namespace: default
  forProvider:
    region: us-east-1
```
After the bucket becomes available
```
kubectl get buckets.s3.aws.upbound.io
NAME                        READY   SYNCED   EXTERNAL-NAME               AGE
upbound-test-bucket-szdjn   True    True     upbound-test-bucket-szdjn   17m
```
The secret has no data:
```
kubectl get secret
NAME          TYPE                                DATA   AGE
test-bucket   connection.crossplane.io/v1alpha1   0      19m

```

### What environment did it happen in?

* Crossplane Version: 1.13.2
* Provider Version: 0.40.0
* Kubernetes Version: 1.27.4
* Kubernetes Distribution: EKS
