### ISSUE TITLE
If tag contains `&` - error `apply failed: creating KMS Key: TagException: Invalid tag: `

### ISSUE THREAD

**Issue by dee-kryvenko** [upbound/provider-aws#922]
### What happened?

If I try to create a resource like this:

```yaml
apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
  name: kryvenkd-test
spec:
  deletionPolicy: Delete
  forProvider:
    deletionWindowInDays: 7
    keyUsage: ENCRYPT_DECRYPT
    region: us-east-1
    tags:
      Owner: My & My Team
  providerConfigRef:
    name: provider-aws-local-account
```

I then get this

```yaml
  - lastTransitionTime: "2023-10-12T02:35:47Z"
    message: 'apply failed: creating KMS Key: TagException: Invalid tag: '
    reason: ApplyFailure
    status: "False"
    type: LastAsyncOperation
```

I recon this is not just KMS, possibly a global issue with handling tags.

CloudTrail doesn't tell much:

```
    "errorCode": "TagException",
    "errorMessage": "Invalid tag",
```

Something else I noticed is that `kubectl.kubernetes.io/last-applied-configuration` has it like this `{"Owner":"My \u0026 My Team"}` after apply.

### How can we reproduce it?

Pretty much just apply resource from above.

### What environment did it happen in?

* Crossplane Version: latest
* Provider Version: latest
* Kubernetes Version: v1.26.2
* Kubernetes Distribution: Google Anthos on AWS
