### ISSUE TITLE
RDS Cluster doesn't report allowMajorVersionUpgrade and applyImmediately in status.atProvider  

### ISSUE THREAD

**Issue by irizzant** [upbound/provider-aws#937]
### What happened?

I have installed provider-aws-rds/v0.42.0 and I'm trying to import an existing RDS Cluster in Crossplane with:

```yaml
apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    crossplane.io/external-name: xxx
  name: xxx
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: eu-central-1

```
As far as I can see the status.atProvider populates but it's missing
* allowMajorVersionUpgrade
*  applyImmediately
```yaml
status:
    atProvider:
      allocatedStorage: 1
      arn: arn:aws:rds:eu-central-1:xxx:cluster:xxx
      availabilityZones:
      - eu-central-1a
      - eu-central-1b
      - eu-central-1c
      backtrackWindow: 0
      backupRetentionPeriod: 14
      clusterMembers:
```

These attributes are listed in status.atProvider in the official docs:
https://marketplace.upbound.io/providers/upbound/provider-aws-rds/v0.42.0/resources/rds.aws.upbound.io/Cluster/v1beta1

### How can we reproduce it?

1. install provider-aws-rds/v0.42.0
2. import an existing RDS instance
3. verify the status is missing the 
### What environment did it happen in?

* Crossplane Version: 1.13.2
* Provider Version:  v0.42.0
* Kubernetes Version: 
`
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
`
* Kubernetes Distribution: 
Kind
