### ISSUE TITLE
Observe resources don't become Ready until they're 10 minutes old

### ISSUE THREAD

**Issue by mbbush** [upbound/provider-aws#966]
### What happened?
When creating a managed resource which uses 
```
spec:
  managementPolicies:
    - Observe
```
I notice that when I create the resource, it reports synced almost immediately, but the `Ready` condition is missing, and the value of `status.atProvider` is `{}`. I logged into the provider pod and I saw the correct external state in `/tmp/{uid}/terraform.tfstate`, but it didn't make it onto the status field of the managed resource until the _next_ run of the reconciliation loop. This happens automatically after 10 minutes, or can be hastened by e.g. putting an annotation on the managed resource.

### How can we reproduce it?
First create an IAM role in your account named `example`. It doesn't matter what's in the trust policy, and it doesn't need any permissions.
Apply this manifest:
```
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    crossplane.io/external-name: example
  name: example
spec:
  forProvider: {}
  managementPolicies:
  - Observe
```

### What environment did it happen in?

* Crossplane Version: 1.12.2
* Provider Version: 0.43.0
* Kubernetes Version:  v1.24.17
* Kubernetes Distribution: EKS
