### ISSUE TITLE
Connect failed with custom Service/Endpoint 

### ISSUE THREAD

**Issue by clementblaise** [upbound/provider-aws#971]
### What happened?

I wanted to test the new release on a local setup (using localstack)

I installed the provider and it got healthy
```
provider-aws                 True                True                xpkg.upbound.io/upbound/provider-aws:v0.44.0                  17m                
```

All the provider MRs have the following events:
```
cannot initialize the no-fork async external client: cannot get terraform setup: could not configure no-fork AWS client: cannot configure no-fork client because the length of assume role chain array is more than 1 or endpoint configuration is not nil
```

Looking at the recent [changes](https://github.com/upbound/provider-aws/blame/main/internal/clients/aws.go) around the client code, it seems related to this [commit](https://github.com/upbound/provider-aws/commit/9d962421ad8ff94686085850372b812f79aff32a)

### How can we reproduce it?

Provider
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v0.44.0
```

ProviderConfig
```
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: hello-world-demo
spec:
  credentials:
    secretRef:
      key: creds
      name: aws-creds
      namespace: crossplane-system
    source: Secret
  endpoint:
    services:
    - iam
    url:
      static: http://localstack.cloud:4566/
      type: Static
  s3_use_path_style: true
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_requesting_account_id: true
 ---
apiVersion: v1
kind: Secret
data:
  creds: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gInRlc3QiCmF3c19zZWNyZXRfYWNjZXNzX2tleSA9ICJ0ZXN0Ig==
metadata:
  name: aws-creds
  namespace: crossplane-system
type: Opaque
```

Example MR
```
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: demo
spec:
  deletionPolicy: Delete
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::000000000000:role/demo"
            },
            "Action": "sts:AssumeRole",
            "Condition": {}
          }
        ]
      }
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: hello-world-demo
```

### What environment did it happen in?

* Crossplane Version: 1.13.2
* Provider Version: 0.44.0
* Kubernetes Version: 1.27.3
* Kubernetes Distribution: kind
