### ISSUE TITLE
v0.44.0 - `Cluster` `eks.aws.upbound.io` unable to select `subnetIds`

### ISSUE THREAD

**Issue by haarchri** [upbound/provider-aws#975]
### What happened?

```
kubectl describe cluster.eks.aws.upbound.io/platform-ref-aws-cnoe-nm9pn-9l46l 
Name:         platform-ref-aws-cnoe-nm9pn-9l46l
Namespace:    
Labels:       crossplane.io/claim-name=platform-ref-aws-cnoe
              crossplane.io/claim-namespace=default
              crossplane.io/composite=platform-ref-aws-cnoe-nm9pn
Annotations:  crossplane.io/composition-resource-name: kubernetesCluster
              crossplane.io/external-name: platform-ref-aws-cnoe-nm9pn-9l46l
              upjet.upbound.io/test: true
API Version:  eks.aws.upbound.io/v1beta1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2023-11-18T14:36:14Z
  Generate Name:       platform-ref-aws-cnoe-nm9pn-
  Generation:          718
  Owner References:
    API Version:           aws.platform.upbound.io/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  XEKS
    Name:                  platform-ref-aws-cnoe-nm9pn-wfzr7
    UID:                   50e377c8-d74d-4829-9184-048993a0f249
  Resource Version:        9953
  UID:                     7f8bc536-e65c-4697-8a98-ba5321503dc9
Spec:
  Deletion Policy:  Delete
  For Provider:
    Region:    us-west-2
    Role Arn:  arn:aws:iam::609897127049:role/platform-ref-aws-cnoe-nm9pn-5l8kf
    Role Arn Ref:
      Name:  platform-ref-aws-cnoe-nm9pn-5l8kf
    Role Arn Selector:
      Match Controller Ref:  true
      Match Labels:
        Role:  controlplane
    Tags:
      Crossplane - Kind:            cluster.eks.aws.upbound.io
      Crossplane - Name:            platform-ref-aws-cnoe-nm9pn-9l46l
      Crossplane - Providerconfig:  default
    Version:                        1.27
    Vpc Config:
      Endpoint Private Access:  true
      Endpoint Public Access:   true
      Subnet Id Selector:
        Match Labels:
          Access:                                       public
          networks.aws.platform.upbound.io/network-id:  platform-ref-aws-cnoe
  Init Provider:
  Management Policies:
    *
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2023-11-18T14:36:23Z
    Message:               cannot resolve references: mg.Spec.ForProvider.VPCConfig[i3].SubnetIds: referenced field was empty (referenced resource may not yet be ready)
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                           Age                From                                              Message
  ----     ------                           ----               ----                                              -------
  Warning  CannotResolveResourceReferences  12m (x3 over 12m)  managed/eks.aws.upbound.io/v1beta1, kind=cluster  cannot resolve references: mg.Spec.ForProvider.RoleArn: referenced field was empty (referenced resource may not yet be ready)
  Warning  CannotResolveResourceReferences  11m (x3 over 12m)  managed/eks.aws.upbound.io/v1beta1, kind=cluster  cannot resolve references: mg.Spec.ForProvider.VPCConfig[i3].SubnetIds: referenced field was empty (referenced resource may not yet be ready)
```

```
kubectl get subnets
NAME                                READY   SYNCED   EXTERNAL-NAME              AGE
platform-ref-aws-cnoe-nm9pn-89k8b   True    True     subnet-0b286a046b6931ea6   13m
platform-ref-aws-cnoe-nm9pn-n8n2q   True    True     subnet-0a9814ca1268efc19   13m
platform-ref-aws-cnoe-nm9pn-nrj7g   True    True     subnet-070abff05f30d8712   13m
platform-ref-aws-cnoe-nm9pn-xqsd6   True    True     subnet-0caaa3fb58c03fe6f   13m
```

```
apiVersion: v1
items:
- apiVersion: ec2.aws.upbound.io/v1beta1
  kind: Subnet
  metadata:
    annotations:
      crossplane.io/composition-resource-name: subnetPublicB
      crossplane.io/external-create-pending: "2023-11-18T14:36:40Z"
      crossplane.io/external-create-succeeded: "2023-11-18T14:36:40Z"
      crossplane.io/external-name: subnet-0b286a046b6931ea6
      upjet.upbound.io/test: "true"
    creationTimestamp: "2023-11-18T14:36:14Z"
    finalizers:
    - finalizer.managedresource.crossplane.io
    generateName: platform-ref-aws-cnoe-nm9pn-
    generation: 4
    labels:
      access: public
      crossplane.io/claim-name: platform-ref-aws-cnoe
      crossplane.io/claim-namespace: default
      crossplane.io/composite: platform-ref-aws-cnoe-nm9pn
      networks.aws.platform.upbound.io/network-id: platform-ref-aws-cnoe
      zone: us-west-2b
[...]
```

### What environment did it happen in?

* Crossplane Version:
* Provider Version:
* Kubernetes Version:  
* Kubernetes Distribution:
