### ISSUE TITLE
EKS NodeGroup with custom AMI fails to update

### ISSUE THREAD

**Issue by moolen** [upbound/provider-aws#976]
This has been fixed in [crossplane-contrib/provider-aws#1633](https://github.com/crossplane-contrib/provider-aws/pull/1633) but it isn't available here.

Given the below `NodeGroup` that runs with a custom AMI i **am able** to create the resources in AWS.
I ran into an issue when i tried to update the NodeGroup (update AMI): 

```
apply failed: error updating EKS Node Group (<cluster>:<node-group>) version: InvalidParameterException: 
You cannot specify the field releaseVersion when using custom AMIs.
```

The releaseVersion has not been set by me, but rather by `provider-aws` when it syncs back the tfstate into the custom resource.
Deleting the `releaseVersion` does not help, it get's reconciled immediately by the provider. The `managedFields` also indicate that this field is owned by the provider.

```yaml
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: "foobar"
spec:
  forProvider:
    amiType: CUSTOM
    launchTemplate:
      - name: example
        version: "$Latest"
    # ...
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: LaunchTemplate
metadata:
  name: example
spec:
  forProvider:
    # ...
    imageId: ami-0b9b30c466935db49
    # ...

```

As seen in [crossplane-contrib/provider-aws#1633](https://github.com/crossplane-contrib/provider-aws/pull/1633) the provider must not set the `releaseVersion` or `version` when `forProvider.AMIType == "CUSTOM"`.
I don't know if this can be done with the existing tooling in `config/eks` or needs a fix in upstream.

### What environment did it happen in?

* Crossplane Version: 1.14.1
* Provider Version: 0.43.1
* Kubernetes Version: 1.27.7-eks
* Kubernetes Distribution: EKS
