### ISSUE TITLE
AWS Provider controller can't bind subnet to a vpc it creates

### ISSUE THREAD

**Issue by NeonOriginal** [upbound/provider-aws#99]
I am currently having an issue with the AWS Provider spinning up a VPC resource and binding a subnet to it in a Composition.
I am using the Provider resource here w/ current status info
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-aws
spec:
  controllerConfigRef:
    name: debug-config
  ignoreCrossplaneConstraints: false
  package: xpkg.upbound.io/upbound/provider-aws:v0.18.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
status:
  conditions:
  - lastTransitionTime: "2022-10-25T21:22:02Z"
    reason: HealthyPackageRevision
    status: "True"
    type: Healthy
  - lastTransitionTime: "2022-10-25T17:33:28Z"
    reason: ActivePackageRevision
    status: "True"
    type: Installed
  currentIdentifier: xpkg.upbound.io/upbound/provider-aws:v0.18.0
  currentRevision: crossplane-provider-aws-80ff1ee1c639
```

I am trying to setup a CompositeResource that spins up a VPC and have a subnet be created in that VPC.
I am having issues when creating this resource through the Composition resource method.
I have defined a CompositeResourceDefinition, the Composition, and a Claim. However when I spin it up the vpc gets created but the subnet is erroring out.
Am I missing something. I am following the documentation here for the VPC: https://marketplace.upbound.io/providers/upbound/provider-aws/v0.18.0/resources/ec2.aws.upbound.io/Subnet/v1beta1
The idea is to extend this further into RDS instances in the vpc, kubernetes resources in the cluster, etc. with this composition. But this official upbound controller doesn't seem to be able to find the vpc it creates.
I have given the credentials with full admin for testing so it shouldn't be a permission issue.

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xfullappinstances.apps.mbrdna.com
spec:
  group: apps.mbrdna.com
  names:
    kind: XFullAppInstance
    plural: xfullappinstances
  claimNames:
    kind: FullAppInstance
    plural: fullappinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              appName:
                type: string
              region:
                type: string
            required:
              - appName
              - region
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: fullappinstancecomp
  labels:
    crossplane.io/xrd: xfullappinstances.apps.mbrdna.com
    provider: kubernetes-provider
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: apps.mbrdna.com/v1alpha1
    kind: XFullAppInstance
  resources:
  - name: newvpc
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: VPC
      metadata:
        name: newvpc
      spec:
        forProvider:
          cidrBlock: "10.0.0.0/16"
          enableDnsHostnames: true
          tags:
           Name: newvpc
        providerConfigRef:
          name: aws
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.region
      toFieldPath: spec.forProvider.region
  - name: subnet1
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: subnet1
      spec:
        forProvider:
          cidrBlock: "10.0.0.0/24"
          vpcIdRef:
            name: newvpc
        providerConfigRef:
          name: aws
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.region
      toFieldPath: spec.forProvider.region
---
apiVersion: apps.mbrdna.com/v1alpha1
kind: FullAppInstance
metadata:
  namespace: default
  name: testcomp
spec:
  appName: testcomp
  region: us-west-1
  compositionRef:
    name: fullappinstancecomp
  writeConnectionSecretToRef:
    name: me-creds
```
The errors I get for the subnet are:
```
Warning  CannotResolveResourceReferences  15s (x6 over 73s)  managed/ec2.aws.upbound.io/v1beta1, kind=subnet  cannot resolve references: mg.Spec.ForProvider.VPCID: cannot get referenced resource: VPC.ec2.aws.upbound.io "newvpc" not found
```

I cannot find great examples of binding one resource to another in the documents. Any ideas on what is wrong with the provider?

**Comment by turkenh** [comment]
@NeonOriginal VPC IDs are some randomized string generated by AWS, hence you can not reference them by the name of the XP managed resource(MR). You should rather use a selector to find the MR using labels, see [dependencies](https://crossplane.io/docs/v1.9/concepts/managed-resources.html#dependencies) or even better use `matchControllerRef: true` to instruct your subnet to find the VPC as part of the same composition. See [this](https://github.com/upbound/platform-ref-aws/blob/d482251a4c2f23211c7f32845fb826fc48a11aea/package/cluster/network/composition.yaml#L59-L60) as the exact example.

**Comment by haarchri** [comment]
the issue is that the vpc metadata.name is generated with compositions - try this:

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: fullappinstancecomp
  labels:
    crossplane.io/xrd: xfullappinstances.apps.mbrdna.com
    provider: kubernetes-provider
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: apps.mbrdna.com/v1alpha1
    kind: XFullAppInstance
  resources:
  - name: newvpc
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: VPC
      metadata:
        labels:
          resource: vpc
      spec:
        forProvider:
          cidrBlock: "10.0.0.0/16"
          enableDnsHostnames: true
          tags:
           Name: newvpc
        providerConfigRef:
          name: aws
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.region
      toFieldPath: spec.forProvider.region
  - name: subnet1
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: subnet1
      spec:
        forProvider:
          cidrBlock: "10.0.0.0/24"
          vpcIdSelector:
            matchControllerRef: true
            matchLabels:
              resource: vpc
        providerConfigRef:
          name: aws
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.region
      toFieldPath: spec.forProvider.region
```
