### ISSUE TITLE
EKS provider generates empty ConnectionSecret

### ISSUE THREAD

**Issue by DavidZisky** [upbound/provider-aws#995]
### What happened?

When deploying EKS with EKS provider I'm getting empty ConnectionSecret. I specify writeConnectionSecretToRef as per API ref and the secret is being created but it's empty (even long time after EKS is up and running). EKS itself is being created correctly and I can connect to it manually (with AWS CLI)

```
# kubectl -n crossplane-system get secret eks-kubeconfig
NAME             TYPE                                DATA   AGE
eks-kubeconfig   connection.crossplane.io/v1alpha1   0      24m
```

### How can we reproduce it?

```
apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    uptest.upbound.io/timeout: "2400"
  labels:
    testing.upbound.io/example-name: ekseks
  name: sample-eks-cluster2
spec:
  forProvider:
    region: eu-central-1
    roleArnRef:
      name: eks-cluster-role
    vpcConfig:
      - subnetIdRefs:
          - name: ekssubnet1
          - name: ekssubnet2
        endpointPrivateAccess: true
  writeConnectionSecretToRef:
    name: eks-kubeconfig
    namespace: crossplane-system
  providerConfigRef:
    name: awsdefault
```
### What environment did it happen in?

* Crossplane Version: 1.14
* Provider Version: 0.44.0
* Kubernetes Version: 1.28
* Kubernetes Distribution: EKS
